### ISSUE TITLE
Something wrong with <img> tag's percentage length

### ISSUE THREAD

**Issue by frostrain** [ezyang/htmlpurifier#102]
Tested on [http://htmlpurifier.org/demo.php](url)

For `<img src="http://htmlpurifier.org/logo.png" style="width: 25%;">`,
it got `<img src="http://htmlpurifier.org/logo.png" alt="logo.png" />`,  the percentage width was removed.

Also, `<img src="http://htmlpurifier.org/logo.png" width="25%">` can't work

But pixel length work:
`<img src="http://htmlpurifier.org/logo.png" style="width: 100px;">`

**Comment by ezyang** [comment]
To enable percentage-based widths on images, set CSS.MaxImgLength to NULL. This default is to protect against imagecrash attacks. (Though, eight years after this code was added, maybe it's time to change the default.)

**Comment by frostrain** [comment]
I got it, thank you.
