### ISSUE TITLE
Scheme is erased when it's the default scheme

### ISSUE THREAD

**Issue by syl20b** [ezyang/htmlpurifier#103]
My config is : 
```
URI.DefaultScheme = 'data'
URI.AllowedSchemes = ['data => true]
```

The HTMLPurifier_URI::validate() method remove the data scheme from the uri

**Comment by ezyang** [comment]
Hmm, I certainly agree that something odd is going on here, but why isn't the problem simply that the default scheme shouldn't be data?

**Comment by syl20b** [comment]
In my case, i just need only the data scheme to filter my html input. Is it forbidden to do tis ?

**Comment by ezyang** [comment]
I am not entirely sure what you mean here, but:

1. If you mean that you only want data URIs to be allowed, setting URI.AllowedSchemes should be sufficient

2. If you want to call the URI validator on data URIs, just go ahead and call it; no need for setting default scheme.

**Comment by syl20b** [comment]
You're right, I just want data URIs.
I tried to set URI.AllowedSchemes with only data, but that configuration generate an error, due to the abscence of the default scheme (http) in the list of allowed schemes. 
And if I change the default value for URI.DefaultScheme (with data), the URI validator remove the value of the scheme property (because default scheme is equal to the scheme of the URI, and the host is empty).

Maybe I don't understand how to declare the configuration... In this case, help will be welcome :)

**Comment by ezyang** [comment]
Ahhh! So there is the actual bug: we need a way to disable DefaultScheme (this would exclude all URIs that don't have schemes: I imagine this is what you want). Shouldn't be too difficult.

**Comment by syl20b** [comment]
There is a way to avoid this behaviour with scheme object witch the host can be omitted in this PR  (https://github.com/ezyang/htmlpurifier/pull/104)

**Comment by syl20b** [comment]
So, what do you think about the way i suggest to solve this unexpected behaviour ?
If this don't suite your need, i am aware to any suggestion.
