### ISSUE TITLE
PHP 7.1.0 Strange opcache behavior

### ISSUE THREAD

**Issue by Streid** [ezyang/htmlpurifier#108]
Hello everyone! This problem occurs only on PHP 7.1.0 with enabled Zend OpCache.

HTMLPurifier_Strategy_MakeWellFormed::processToken:542
```
// $token = 2
$token = array($token);
// $token = array(1) { [0]=> array(1) { [0]=> *RECURSION* } }
```

After executing this code, the token will be: **array(1) { [0]=> array(1) { [0]=> *RECURSION* } }**
 
My config:

```
$config = \HTMLPurifier_Config::createDefault();
$config->set('HTML.AllowedElements', 'b, i, u, ul, li, ol, blockquote, br, p, a');
$config->set('HTML.AllowedAttributes', ['a.href']);
$config->set('AutoFormat.RemoveEmpty', true);
$config->set('AutoFormat.RemoveEmpty.RemoveNbsp', true);
$config->set('AutoFormat.AutoParagraph', true);
$config->set('Cache.SerializerPath', sys_get_temp_dir());
```

Also, the text should contain no closed tags!

Temporary solution:
```
$tmpToken = $token;
$token = array();
$token[] = $tmpToken;
```

**Comment by ezyang** [comment]
Fascinating miscompilation! Please test #109 and let me know if it resolves the problem.

**Comment by plfort** [comment]
Are you going to release a 4.8.1 ?

**Comment by ezyang** [comment]
It'd be a 4.9. Probably as a good a time as any.

**Comment by trsteel88** [comment]
Did this fix your problem @Streid?
