### ISSUE TITLE
HTML Purifier 4.9.0 just disappear today ?

### ISSUE THREAD

**Issue by vincent-guesnard** [ezyang/htmlpurifier#113]
Hello,

What happens to HTML Purifier 4.9.0 (release on 2017 January, 13) ? Seems that it has been removed from the Web.

Do we have to downgrade for 4.8.0 ?

Thank you

Best regards

V

**Comment by haeber** [comment]
It's still listed as v4.9.0 in https://packagist.org/packages/ezyang/htmlpurifier

**Comment by ezyang** [comment]
Oops, this is my fault: I started making commits to cut 4.9.0 but then decided I wanted to merge #112 before the release, and I backed it out. @vincent-guesnard, is there a course of action I can take which is most convenient for you (e.g., adding those commits back to GitHub).

**Comment by vincent-guesnard** [comment]
Don't worry, it's OK :)

I was just anxious about a potential security issue which force you to make a rollback. (and force us to do the same)

I'll shutdown my warning on my github API on your project for some days, until you release the 4.9.0.

Thanks you for all you've done :) You have no idea how it helps me to deal with dirty HTML automaticly written by CKEditor or TinyMCE.

Best regards,

V

**Comment by araines** [comment]
Would be good if we could have it removed from packagist given that it no longer exists.

**Comment by ezyang** [comment]
packagist is fixed up, apparently.
