### ISSUE TITLE
Html Purifier creates invalig tags

### ISSUE THREAD

**Issue by trandaihung** [ezyang/htmlpurifier#114]
I found it no where.

So I got this basic config of htmlpurifier

```
'HTML.Doctype'             => 'HTML 4.01 Transitional',
'HTML.Allowed'             => 'b,strong,i,em,u,img[src|alt|width|height]',
'CSS.AllowedProperties'    => '',
'AutoFormat.AutoParagraph' => false,
'AutoFormat.RemoveEmpty'   => true
```

And the input

```
test
<abc>
<<abc>>
```

In the output, htmlpurifier creates a new <abc></abc> tag, which I don't know why this happens

```
test
<abc></abc>
&lt;<abc>&gt;</abc>
```

I've tried Core.EscapeInvalidTags but it had no use.
Which could be the reason here? Are there settings I need to turn on.

**Comment by ezyang** [comment]
Based on the output you've posted, I'm pretty sure something after HTML Purifier is unescaping entities. Try inputting `&lt;b&gt;&lt;/b&gt;`; what do you get out?

**Comment by trandaihung** [comment]
@ezyang I'm sorry, it is my bad. 
I tested your input, and suddenly figured out the incorrect display is because of Ckeditor parser. The output I posted above is in Ckeditor, not in the real website.
Still it took me an hour because I trusted Ckeditor ...

Hope this will help other.

**Comment by ezyang** [comment]
Good!
