### ISSUE TITLE
Unnecessary Codes

### ISSUE THREAD

**Issue by irfanevrens** [ezyang/htmlpurifier#116]
Hello

Starting line L568 [  if ($injector > -1) { ] there is unnecessary codes in IF block.

https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/Strategy/MakeWellFormed.php#L568

I think it shoud be delete.

Thanks.

**Comment by ezyang** [comment]
Hello @irfanevrens, can you explain in more detail why you think the code there is not necessary? You might be right but it is not obvious to me.

**Comment by irfanevrens** [comment]
hello ezyang,

        if ($injector > -1) {
            // determine appropriate skips
            $oldskip = isset($old[0]) ? $old[0]->skip : array();
            foreach ($token as $object) {
                $object->skip = $oldskip;
                $object->skip[$injector] = true;
            }
        }
        return $r;

what is the aim of "IF Block"?

if $injector greater than -1 then $oldskip whether $old[0]->skip or empty array. Then looping $token array and every iteration has no valuable thing. 

if it is not obvious yet, please explain these codes (IF Block).

**Comment by ezyang** [comment]
I still didn't understand, so I went into the code and wrote some commentary about why it's setup the way it is. I definitely agree that it is not clear what this code is supposed to do, but I don't really want to change it unless there's a clear idea for why the change is for better.
