### ISSUE TITLE
Error (0) : HTML Purifier autoloader

### ISSUE THREAD

**Issue by jricher-dev** [ezyang/htmlpurifier#117]
Hi, I have an error when I try to use the already implemented library in a third-party directory.
Here is the error:

```Error (0) : HTML Purifier autoloader registrar is not compatible with non-static object methods due to PHP Bug #44144; Please do not use HTMLPurifier.autoload.php (or any file that includes this file); instead, place the code: spl_autoload_register(array('HTMLPurifier_Bootstrap', 'autoload')) after your own autoloaders.```

And i don't know how to fix ...

my code to load the library is : 
`require_once '3rdparties/htmlpurifier/HTMLPurifier.auto.php';`

**Comment by ezyang** [comment]
As the message suggests, you will need to replace the require of `HTMLPurifier.auto.php` with an include of `HTMLPurifier/Bootstrap.php`, and then add the code mentioned above.

Alternatively, upgrade the version of PHP being used on your server.

Alternatively, try this:

```
require '3rdparties/htmlpurifier/HTMLPurifier.path.php';
require 'HTMLPurifier.includes.php';
```
