### ISSUE TITLE
problem with adding attributes

### ISSUE THREAD

**Issue by julesbl** [ezyang/htmlpurifier#126]
Hi
Been attempting to add attributes to the a tag
				$filter_config = \HTMLPurifier_Config::createDefault();
				$def = $filter_config->getHTMLDefinition(true);
				$def->addAttribute('a', 'id', 'ID');
				$def->addAttribute('a', 'name', 'ID');
				$filter = new \HTMLPurifier($filter_config);
Just cant seem to get this to work, been following the documentation religiously. Its just to allow anchors.
I figure it must be something to do with cacheing but adding commands such as set('Cache.DefinitionImpl', null); has no effect.

Version 4.9.1, PHP7.0

**Comment by ezyang** [comment]
This is not necessary for IDs. See http://htmlpurifier.org/docs/enduser-id.html
