### ISSUE TITLE
PHP 7.2: "__autoload() is deprecated, use spl_autoload_register() instead"

### ISSUE THREAD

**Issue by zerocrates** [ezyang/htmlpurifier#154]
The mere presence of the `__autoload` function definition, even inside the conditional, seems to raise this warning on PHP 7.2. It's just a deprecation warning but it will crop up and cause problems for people running tests and things like that (where I saw it).

Simply eliminating the __autoload fallback from HTMLPurifier.autoload.php
would quiet the complaint. As it's only support for ancient versions it might be prudent to do so.

Otherwise, I suppose you could split off the __autoload definition into a separate file that would only be conditionally `include`'d, thus making it so the problematic definition isn't visible when it's not needed.

**Comment by ezyang** [comment]
OK! I'll take a patch that does this.

**Comment by zerocrates** [comment]
which? dropping the fallback or separating it out?

**Comment by ezyang** [comment]
Separating it out please!

**Comment by 3alampro** [comment]
@ezyang kindly can we have release for this so we can update our project with composer update

**Comment by ezyang** [comment]
OK, one of these days :)

**Comment by brandonfarber** [comment]
Anything we can do to help speed up getting a new build? HTMLPurifier is essentially broken on PHP 7.2 presently, which is general release and thus has to be supported in most projects.

**Comment by ezyang** [comment]
4.10.0 is out.

**Comment by guruskid** [comment]
replace line 45
function __autoload($classname)
{
PHPMailerAutoload($classname);
}

with

spl_autoload_register(function($class) {
PHPMailerAutoload($classname);
});

**Comment by SmartGuyCodes** [comment]
//Auto load classes
1. OLD WAY EXAMPLE
// function __autoload($className){
// // function spl_autoload_register($className){
// 	if(file_exists(DIR_FS_CLASSES . "class." . $className . ".php"))
// 		include DIR_FS_CLASSES . "class." . $className . ".php";
// }

2. NEW WAY EXAMPLE
spl_autoload_register(function($className) {
    // include 'classes/' . $class . '.class.php';
    if(file_exists(DIR_FS_CLASSES . "class." . $className . ".php"))
		include DIR_FS_CLASSES . "class." . $className . ".php";
});
