### ISSUE TITLE
Support for b64 images

### ISSUE THREAD

**Issue by psociety** [ezyang/htmlpurifier#162]
base64 images are not supported and aren't harmful:
`<img src="data:image/png;base64,i...`

**Comment by pprins** [comment]
@psociety you can do this. 
```php
$config->set('URI.AllowedSchemes', ['data' => true]);
```

**Comment by qwebdev** [comment]
@pprins, @psociety 

Something like this would also allow for regular images via the src attribute:

` 'URI.AllowedSchemes' => ['data' => true,'src'=>true,'http' => true, 'https' => true,],`

**Comment by tkant** [comment]
People can close this one. Allowing URI schemes works.

**Comment by ezyang** [comment]
Yes, it's not enabled by default but you can turn it on pretty easily.
