### ISSUE TITLE
PHP 7.2.2 deprecated functions

### ISSUE THREAD

**Issue by cappadaan** [ezyang/htmlpurifier#165]
htmlpurifier 4.9.3 + PHP 7.2.2 give these notices:

PHP Deprecated:  idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /HTMLPurifier/HTMLPurifier/AttrDef/URI/Host.php on line 100

PHP Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead in /HTMLPurifier/HTMLPurifier.autoload.php on line 17

**Comment by Pittiplatsch** [comment]
Already fixed with #148.
I'm awaiting a new release as well.
