### ISSUE TITLE
Allow installing "dev-master" via composer

### ISSUE THREAD

**Issue by Pittiplatsch** [ezyang/htmlpurifier#166]
While waiting for an official release of #148, we tried to install the respective commit ce0ede24ded2e05489f5bab50cc53426599532e4 via composer using the default packagist repo:
```
"require": {
    "ezyang/htmlpurifier": "dev-master#ce0ede24ded2e05489f5bab50cc53426599532e4"
}
```

This however doesn't work:
```
[InvalidArgumentException]
  Could not find package ezyang/htmlpurifier in a version matching dev-master#ce0ede24ded2e05489f5bab50cc53426599532e4
```
for the reason that your `dev-master` isn't available via Packagist: https://packagist.org/packages/ezyang/htmlpurifier
(compare to pkpass @ Packagist: https://packagist.org/packages/pkpass/pkpass, where `dev-master` is directly available, and therefore directly installable via composer w/ default Packagist repo)

The only workaround is to include your repo via Github directly:
```
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/ezyang/htmlpurifier.git"
        }
    ],
```
which completely clones your repo, making each commit accessible via `dev-master#commithash` syntax.

**Comment by aaronpk** [comment]
I ran into this same problem. I would definitely appreciate if you included dev-master on packagist!

**Comment by ezyang** [comment]
I fixed the SPDX license signifier which was preventing master from being imported, so I now see a dev-master clicky on the sidebar: https://packagist.org/packages/ezyang/htmlpurifier#dev-master

However, despite having setup Packagist integration, I still see:

> This package is not auto-updated. Please set up the GitHub Service Hook for Packagist so that it gets updated whenever you push!

So it seems that we may not be getting updates. How can I debug this problem?

**Comment by ezyang** [comment]
Fixed it. https://github.com/composer/packagist/issues/882
