### ISSUE TITLE
Convert & to &amp; and it impact in database saving

### ISSUE THREAD

**Issue by bhavinrshah** [ezyang/htmlpurifier#177]
Convert `&` to `&amp;` and it impacts on database saving. It should not convert `&` and could not find any settings to restrict the same.

**Comment by ezyang** [comment]
Standards conformant XML does not permit bare ampersand, and HTML Purifier acts accordingly. Can you point to some guidance which indicates that ampersands should not be escaped?

**Comment by bhavinrshah** [comment]
In html form, if a user put a name of title with `&` then it saves with `&amp;` so it will create problem. In this case, it should save as `&`
