### ISSUE TITLE
In html form, if a user put a name of title with `&` then it saves with `&amp;` so it will create problem. In this case, it should save as `&`

### ISSUE THREAD

**Issue by bhavinrshah** [ezyang/htmlpurifier#178]
In HTML form, if a user puts a name of the title with `&` then it saves with `&amp;` so it will create the problem. In this case, it should save as `&`

Do you have any suggestion to fix?

**Comment by ezyang** [comment]
Do you want html tags to be allowed in titles? If the answer is NO, you should not use HTML Purifier (use htmlspecialchars instead). Otherwise, the current behavior is correct.

**Comment by bhavinrshah** [comment]
I don't want to allow HTML tags in title, only thing if someone adds with `TEST & TEST` so it should save as same instead of `TEST &amp; TEST`.

**Comment by bhavinrshah** [comment]
can we use `HTMLPurifier_Lexer` class with `parseText` method which convert backs `&amp;` to `&`? Is it reliable?

**Comment by ezyang** [comment]
If you don't want to use HTML tags, don't use HTML Purifier. Don't do any processing when you save the title, and htmlspecialchars it when you render it on a page.
