### ISSUE TITLE
idn_to_ascii() expects parameter 2 to be integer, string given

### ISSUE THREAD

**Issue by ak868308** [ezyang/htmlpurifier#180]
ezyang/htmlpurifier/library/HTMLPurifier/AttrDef/URI/Host.php(100): idn_to_ascii('vimeo.com[remove]', 'IDNA_NONTRANSIT...', 'INTL_IDNA_VARIA...')

idn_to_ascii() expects parameter 2 to be integer, string given

**Comment by bytestream** [comment]
Probably something to do with what version of libidn you've got installed, suggest to add phpinfo output to this issue. https://github.com/php/php-src/blob/master/ext/intl/idn/idn.c#L75

Similar issue described here: https://stackoverflow.com/questions/17360179/idn-to-ascii-not-working-in-php-5-4-16-centos6

**Comment by ezyang** [comment]
This was fixed in #171
