### ISSUE TITLE
Enhance error messages (to use HTMLPurifier as just an XSS scanner)

### ISSUE THREAD

**Issue by TolstoyDotCom** [ezyang/htmlpurifier#185]
I just want to give HTMLPurifier some HTML and check if the HTML has anything questionable, without changing the HTML.

The closest seems to be using _CollectErrors_, however that just provides nondescript messages like _"rel attribute on &lt;a&gt; removed"_. Is there a way to add in more details, such as the context, the contents of the rel attribute, etc.?

Or, is there another way to just determine if some HTML contains something bad?

**Comment by ezyang** [comment]
No, this isn't really something HTML Purifier was designed to do, and it will probably never support this feature.
