### ISSUE TITLE
Command injection vulnerabilities

### ISSUE THREAD

**Issue by chalbert-edr** [ezyang/htmlpurifier#192]
There were a couple of vulnerabilities found during a scan of htmlpurifier pertaining to command injection. While these may not be vulnerabilities with the src, we can remove these flags safely and thus making this package secure in the eyes of security experts. 

These permit command injection:
* e()
* release2-tag.php
* release1-update.php

There are few options on addressing: whitelist commands, remove, refactor the code or a combination.

**Comment by chalbert-edr** [comment]
Here's a PR with the changes: https://github.com/ezyang/htmlpurifier/pull/193

**Comment by ezyang** [comment]
I replaced flush.php with a shell script, and renamed release1-update.php without a php extension, for defense in depth. (I don't think there was actually any vulnerability.)
