### ISSUE TITLE
Whitelist `<input type=checkbox>` only

### ISSUE THREAD

**Issue by glensc** [ezyang/htmlpurifier#213]
I've trying to come up with a configuration that allows forms, but only `<input type=checkbox>`, but not with any success. i.e to use https://github.com/lossendae/commonmark-task-lists/

so currently I have enabled `'HTML.Trusted'` which also enables `<script>` :/

the stackoverflow threads do not end up with solutions either. in fact, I'd be even fine enabling whole forms component. but failed to succeed on that either.

**Comment by xemlock** [comment]
Hi @glensc, try adding the following to your config:

```php
[
    'HTML.Trusted' => true,
    'HTML.ForbiddenElements' => ['script', 'noscript'],
]
```

That should prevent script-related elements from being accepted.

**Comment by glensc** [comment]
@xemlock thanks, for the hint, will try it.

but this seems counterproductive, i.e htmlpurifier was supposed to be whitelist based, and this example is the exact opposite what htmlpurifier was supposed to do :(

**Comment by glensc** [comment]
hmm, I think this option doesn't exist :

```
app.WARNING: E_USER_WARNING: Value for HTML.ForbiddenElements is of invalid type, should be lookup invoked on line 135 in file src/Markdown.php
```

```
ezyang/htmlpurifier                v4.10.0              Standards compliant...
xemlock/htmlpurifier-html5         v0.1.10              HTML Purifier defin...
```

**Comment by xemlock** [comment]
@glensc Yeah, I agree that at the moment enabling/disabling modules is not granular enough. But I'm thinking about doing something about it in [htmlpurifier-html5](https://github.com/xemlock/htmlpurifier-html5).
