### ISSUE TITLE
Fortify Scan - Command Injection - portal/vendor/ezyang/htmlpurifier/maintenance/flush.php

### ISSUE THREAD

**Issue by AkashGoenka** [ezyang/htmlpurifier#216]
Hi,

We had a fortify scan on our code base to check for possible security vulnerabilities and the following has been reported from this library, request you to look into it. 

**Issue Description** - 
Executing commands from an untrusted source or in an untrusted environment can cause an application to execute malicious commands on behalf of an attacker.

**Recommendation Offered** - 
Do not allow users to have direct control over the commands executed by the program. In cases where user input must affect the command to be run, use the input only to make a selection from a predetermined set of safe commands.

**Occurences** - 

1. portal/vendor/ezyang/htmlpurifier/maintenance/flush.php, line 17
2. portal/vendor/ezyang/htmlpurifier/maintenance/flush.php, line 22

**Comment by glensc** [comment]
what version? link to source code at least with appropriate version?

**Comment by ezyang** [comment]
flush.php doesn't exist on master.
