### ISSUE TITLE
INTL_IDNA_VARIANT_2003's deprecation causes errors in PHP 7.2

### ISSUE THREAD

**Issue by benjaminkohl** [ezyang/htmlpurifier#234]
This issue came up on [another issue thread ](https://github.com/ezyang/htmlpurifier/issues/163#issuecomment-532331899) but it was requested that I file a new bug for it. I'll describe it to the best of my understanding. The INTL_IDNA_VARIANT_2003 constant has been deprecated in PHP 7.2 but it remains as the default value of third parameter of the idn_to_ascii() function. In [Host.php](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/AttrDef/URI/Host.php#L103), the code checks for two constants to be defined then falls back on calling idn_to_ascii() with the default parameters resulting in errors in PHP 7.2.

I don't know where those constants are supposed to be defined nor do I know what their values should be. Additionally, I don't know how that function should be called in the event they are not defined (in PHP 7.2). In other words, I wish I could help but I have no idea what the appropriate fix is.

![host_php](https://user-images.githubusercontent.com/1012180/67115894-3b6ac500-f1ad-11e9-938c-559eb7efcc8d.png)

**Comment by ezyang** [comment]
This is fixed on master.
