### ISSUE TITLE
Class HTMLPurifier_Language_en_x_test does not comply with psr-0 autoloading standard

### ISSUE THREAD

**Issue by xpetter** [ezyang/htmlpurifier#246]
I get this from composer:
Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185

**Comment by ricardomartos** [comment]
Same here

**Comment by cap-akimrey** [comment]
Same Composer notice here, but citing psr-4 non-compliance:
Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185

**Comment by maxxscho** [comment]
Same here with PSR-0 non compliance:

```
Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
```

**Comment by tgfarias** [comment]
`Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`
Same here

**Comment by sebastiansulinski** [comment]
And here.

**Comment by lphilps** [comment]
It appears that the problem is that the class name
"HTMLPurifier_Language_en_x_test"
doesn't match the file name
"en-x-test.php".

Composer v1.10.0 started producing this error, previous versions of composer didn't care.

Any chance of getting a new release that fixes this?

**Comment by ezyang** [comment]
We should probably just delete this file and the tests associated with it.

**Comment by maxxscho** [comment]
Since there aren't any tests in this file, I guess nobody will miss it 😄

**Comment by roelofr** [comment]
The file isn't a test, it's used for a test though.

https://github.com/ezyang/htmlpurifier/blob/b81690c17eae5dbea7557d1f359af8dd17e9beef/tests/HTMLPurifier/LanguageFactoryTest.php#L37-L38

The `HTMLPurifier_LanguageFactoryTest` should be re-written to use a dev-only response, which would remove the file from autoloading.

**Comment by kghbln** [comment]
Will be cool to get rid of this warning. People are already starting to duplicate this issue here.

**Comment by Jimbolino** [comment]
The problem was actually fixed some time ago: https://github.com/ezyang/htmlpurifier/commit/4faca32a4d4b8152d17956606e1fb5043fcc1f10

Maybe it's time for a new v4.13.0 release, because most people require a stable version in their projects

**Comment by roelofr** [comment]
In my tests Composer will still throw the warning, despite excluding them from the classmap (I don't know why, seems weird to me).

**Comment by Jimbolino** [comment]
I think you are trying to exclude files that are part of vendor/ezyang/htmlpurifier.
With me the errors disappeared when i switched my dependecy from "^4.7" to "dev-master"

**Comment by roelofr** [comment]
Hmm, could be. I was replying from the top of my head.

A tag is absolutely a good idea.

**Comment by williamdes** [comment]
https://github.com/ezyang/htmlpurifier/blob/master/.gitattributes could be used to exclude the file from composer vendor bundles
But fixing the real issue is the best option.

**Comment by jbdelhommeau** [comment]
Bug will be fixed with this commit : https://github.com/ezyang/htmlpurifier/commit/4faca32a4d4b8152d17956606e1fb5043fcc1f10 the 31 Oct 2019 juste after the laster release 28 Oct 2019.

 Can you release a new version to fix it please !?

**Comment by roelofr** [comment]
Basically everyone is waiting for a tag.

**Comment by jbdelhommeau** [comment]
Poke @ezyang !

**Comment by ezyang** [comment]
4.13.0 is tagged and released
