### ISSUE TITLE
'Undefined variable: array' after updateing to laravel 7

### ISSUE THREAD

**Issue by GabMic** [ezyang/htmlpurifier#248]
Im am using php 7.4.2
After upgrading to laravel 7, i have this issue for some reason.

Undefined variable: array

In here:

 * @return string[] Array of purified HTML

 */

public function purifyArray($array_of_html, $config = null)

{

    $context_array = array();

    foreach($array_of_html as $key=>$value){

        if (is_array($value)) {

            $array[$key] = $this->purifyArray($value, $config);

        } else {

            $array[$key] = $this->purify($value, $config);

        }

        $context_array[$key] = $this->context;

    }

    $this->context = $context_array;

    return $array;

}

**Comment by ezyang** [comment]
This is fixed on master
