### ISSUE TITLE
Depraction warning

### ISSUE THREAD

**Issue by C0kkie** [ezyang/htmlpurifier#252]
Hello,

if i install htmlpurifier via composer, i get the followin message

 Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by roelofr** [comment]
See #246

**Comment by lptn** [comment]
it's good to know that it will not break anything, but also be great to ret rig of this warning in console

**Comment by ertuzio** [comment]
> See #246
> 
> The file is only used for tests, nothing will break.

It's not important for what the file is used...
The file doesn't comply with psr-0 autoloading standard and that is the problem.

**Comment by roelofr** [comment]
> This should be fixed before the composer v2.0 is out

Should it? Composer 2 will simply not load it (this project's tests will likely start to fail at that point, but users won't notice)

Besides, I created a fix in #253, but it's still open :disappointed:

**Comment by ezyang** [comment]
Fixed on master.
