### ISSUE TITLE
The library purified the img tags, no matter what...

### ISSUE THREAD

**Issue by totumfaktum88** [ezyang/htmlpurifier#255]
Hi there,

i started to use this library from composer: : ^4.12 - PHP 7.3.

I tried clean multiple html files (generated with libreoffice), what contains images with similar external http/https urls and data URI.
All of this images removed. Can you help me?

I tried multiple of configs but not working.

Here is the last one config:

```php
<?php
$purifierConfig = \HTMLPurifier_Config::createDefault();
                $purifierConfig->set('HTML.Doctype', 'HTML 4.01 Transitional');
                $purifierConfig->set('HTML.Allowed', 'a[href|title],img[src],em,strong,cite,blockquote,code,ul,ol,li,dl,dt,dd,p,br,h1,h2,h3,h4,h5,h6,span,*[style]');
                $purifierConfig->set('HTML.Trusted', true);
                $purifierConfig->set('URI.AllowedSchemes', [
                    "data" => true,
                    "http" => true,
                    "https" => true,
                    "file" => true,
                ]);
```

What's missing?

Img tags looks like from generated source:
`<img src="data:image/png;base64," name="title" align="bottom" width="201" height="180" border="0"/>
<img src="https://external.url.tld/image.jpg" name="title" align="bottom" width="201" height="180" border="0"/>
`

Thx for your help!

**Comment by ezyang** [comment]
You need to allow `alt` as an attribute on img, as it is a required attribute

**Comment by ezyang** [comment]
What is your update on config

**Comment by totumfaktum88** [comment]
> What is your update on config

```php
<?php
$purifierConfig = \HTMLPurifier_Config::createDefault();
$purifierConfig->set('HTML.Doctype', 'HTML 4.01 Transitional');
$purifierConfig->set('HTML.Allowed', 'a[href|title],img[src|alt],em,strong,cite,blockquote,code,ul,ol,li,dl,dt,dd,p,br,h1,h2,h3,h4,h5,h6,span,*[style]');
 $purifierConfig->set('URI.AllowedSchemes', [
  "data" => true,
   "http" => true,
   "https" => true,
  "file" => true,
]);
```

**Comment by ezyang** [comment]
If you print your input HTML from PHP before purifying it what does it say?

**Comment by totumfaktum88** [comment]
Uhh god. I found a regex replace what preprocess the source before run the purifier. After removed this section the library worked well.

Thanks for your help!
