### ISSUE TITLE
New release to improve PHP 7.4 support

### ISSUE THREAD

**Issue by MrMitch** [ezyang/htmlpurifier#261]
Hi :wave: ,

At the beginning of the year, PR #243 was merged. It improves PHP 7.4 support by removing a deprecation notice that was caused by a wrong parameter order when calling `implode()`.

**I was wondering if you would be willing to tag a new patch release that would include this PR. The last release dates back to october of last year and does not include this fix.**

This would be allow people (like us) who rely implicitly on `ezyang/htmlpurifier` to fix their support on PHP 7.4.

In our case, we use [caxy/php-htmldiff](https://github.com/caxy/php-htmldiff/blob/master/composer.json#L23) which requires `"ezyang/htmlpurifier": "^4.7"`.

Tagging a new minor release that includes #243 would allow us to run `composer update ezyang/htmlpurifier` and get the fix without having to wait for `caxy/php-htmldiff` to update its composer.json.

PHP 7.4 was released in november of last year and it is the current stable version, so I think more and more people will be using htmlpurifier with PHP 7.4. 

If you are willing to consider this, please let me know if there is anything I can do to help in the release process.

Best regards.

**Comment by MrMitch** [comment]
For reference, here are the 8 unreleased commits that have been pushed between the last version (4.12.0) and now : https://github.com/ezyang/htmlpurifier/compare/v4.12.0...master

**Comment by Jimbolino** [comment]
@ezyang could you tag a new release? this would make a lot of people happy :)

**Comment by ezyang** [comment]
4.13.0 is tagged and released
