### ISSUE TITLE
[Solved] &nbsp; is (not) wrongly converted to spaces

### ISSUE THREAD

**Issue by MrPetovan** [ezyang/htmlpurifier#280]
Hi,

I've encountered an issue using HTML Purifier's default configuration, `&nbsp;` entities are wrongly converted to regular spaces even though the intent isn't the same at all:
```php
$config = \HTMLPurifier_Config::createDefault();
$HTMLPurifier = new \HTMLPurifier($config);
$HTMLPurifier->purify('&nbsp;'); // returns ' '
```
All the existing configuration directives related to `&nbsp;` are about removing empty elements but it seems that keeping them as is isn't possible with the current version.

**Comment by MrPetovan** [comment]
Never mind, after looking into the serialized Entities Lookup data file, I realized it is converting these entities to UTF-8 non-breakable space characters (`C2A0` in hexadecimal), so I was able to either convert them back to entities or use them as is in a HTML document which I didn't expect to work.

**Comment by Daijobou** [comment]
@MrPetovan If there is no issue, close the unnecessary ticket.

**Comment by Tofandel** [comment]
Any way to disable this replacement?

**Comment by ezyang** [comment]
No. You can manually string replace Unicode back into entity if you really want
