### ISSUE TITLE
Config to remove Javascript only

### ISSUE THREAD

**Issue by ybelenko** [ezyang/htmlpurifier#282]
Hey, there! Thanks for a great tool.

However I read documentation third time already and still don't know how to configure HTMLPurifier to sanitize email templates provided by user. I don't need to fix or clean them but remove Javascript. Default config removes `<head>` completely with all CSS declarations.

### What I need:
1. Remove all Javascript and security vulnerabilities. (I guess stripping Javascript is 99% of the job).
2. Keep everything else in original state.

### What I don't need:
1. Strip head, css, unknown tags etc.
2. Autoformatting
3. Fixing tags and properties

It would be great to have this user case in documentation.

**Comment by ezyang** [comment]
Not supported. Full HTML file purification is something that has been requested, but the recommendation is just to extract out the body and then re-frame it yourself. There's a config option for it.

**Comment by ybelenko** [comment]
@ezyang Hmmm, can I add `<head>` `<link>` and `<body>` to list of allowed tags(`HTML.AllowedElements`)?
