### ISSUE TITLE
PHP linter warnings.

### ISSUE THREAD

**Issue by Maikuolan** [ezyang/htmlpurifier#287]
Ran a linter over the htmlpurifier codebase just now; These results were produced:

```
PHP Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead in ./extras/HTMLPurifierExtras.autoload-legacy.php on line 10
Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in ./extras/HTMLPurifierExtras.autoload-legacy.php on line 10
```

If wanted, I could write a quick PR for this, but I'm not sure whether this is something the maintainers are concerned about or would want a PR for, so figured it would better to just create the issue here before doing anything else. :-)

**Comment by bytestream** [comment]
The deprecation notice in modern PHP versions was handled by https://github.com/ezyang/htmlpurifier/pull/156 so I don't think a PR is necessary.

**Comment by Maikuolan** [comment]
Sounds good. :+1:

I'll close this now then.
