### ISSUE TITLE
Is a new release planned?

### ISSUE THREAD

**Issue by tobiastom** [ezyang/htmlpurifier#304]
Hi. I'm currently trying to use htmlpurifier with PHP 8 and I am getting the following syntax error:

```
Parse error: ./vendor/ezyang/htmlpurifier/library/HTMLPurifier.autoload-legacy.php:10
     8|  */
     9| 
  > 10| function __autoload($class)
    11| {
    12|     return HTMLPurifier_Bootstrap::autoload($class);
```

As I can see this issue was fixed in https://github.com/ezyang/htmlpurifier/commit/4285590c90a1eaf36eb6ae147cc1cbfa7aa546a6#diff-b612c84ece435337010ca64e81530a73be5f6109399945520676881e90e56f74. Unfortunately the latest release from 29 Jun 2020 does not contain this fix.

Would it be possible to release a new version that makes it compatible with PHP 8? Are there any blockers?

**Comment by ezyang** [comment]
nope i just have to find time to do it. thanks for the kick

**Comment by bytestream** [comment]
@ezyang we could integrate semantic release so releases are automatic based on feat/fix commit messages?

**Comment by tobiastom** [comment]
@ezyang Thank you for your reply. Looking forward to the release! 😀

**Comment by ezyang** [comment]
@bytestream Sure. How do we do that?

**Comment by bytestream** [comment]
> @bytestream Sure. How do we do that?

I'll send a PR when I get time, but it just requires you to set a GitHub token so it can automate git pushes, publishing releases etc.

**Comment by pyres01** [comment]
邮件已收到，谢谢！
