### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by gopi-imp** [ezyang/htmlpurifier#309]
php 7.3, master / 4.13 / 4.12

Hi, I'm getting a vulnerability issue in the package as scanned by **BlackDuck** tool , its saying that internally the package uses Yii php framework V 1.1.14 which has high security risk

Attached screenshots for reference from BlackDuck scan result

![image (1)](https://user-images.githubusercontent.com/96512717/147063413-76175202-4dc7-4a6d-84e5-5c9c79f63071.png)
![image (2)](https://user-images.githubusercontent.com/96512717/147063420-6c13321f-25a6-4383-ae9a-e1c01cf471e0.png)

**Comment by bytestream** [comment]
Which file is it referring to?

**Comment by PHPGangsta** [comment]
The screenshots are bad quality, hard to read anything.
I would say it's the "ConfigForm.js" in the "Yii Framework". Has nothing to do with htmlpurifier?

**Comment by gopi-imp** [comment]
> Which file is it referring to?

It feels strange that it is pointing to js file (check first screenshot), referring to configForm.js  
Path : vendor/ezyang/htmlpurifier/library/HTMLPurifier/Printer/ConfigForm.js

**Comment by gopi-imp** [comment]
> The screenshots are bad quality, hard to read anything. I would say it's the "ConfigForm.js" in the "Yii Framework". Has nothing to do with htmlpurifier?

i have updated the screenshots

**Comment by PHPGangsta** [comment]
@gopi-imp Thanks for details and updated screenshots 👍 

https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/Printer/ConfigForm.js
The File only has 2 lines, and the content has never changed in the past. Which version of htmlpurifier is your project using? Is the content of your local file the same?

**Comment by gopi-imp** [comment]
@PHPGangsta Im Using Version 4.13 , yes the contents are same, i know it feels strange that it's pointing to js file , but the scan results are as it is.

**Comment by bytestream** [comment]
There's no vulnerability in the specified file.

It looks like it's only used for http://htmlpurifier.org/phorum/

**Comment by ezyang** [comment]
I'm guessing this JS file was copy pasted into a vulnerable version of Yii framework and your static analysis tool has therefore concluded that the entire library is vulnerable. Not actionable.
