### ISSUE TITLE
PHP 8.1 Deprecated funcs

### ISSUE THREAD

**Issue by xkpx64** [ezyang/htmlpurifier#311]
Deprecated: Return type of HTMLPurifier_PropertyListIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Xampp\htdocs\libs\formr\HTMLPurifier.standalone.php on line 8340

Deprecated: Return type of HTMLPurifier_StringHash::offsetGet($index) should either be compatible with ArrayObject::offsetGet(mixed $key): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Xampp\htdocs\libs\formr\HTMLPurifier.standalone.php on line 8458

**Comment by zerocrates** [comment]
Yes, that PR included the attributes used to silence those two deprecation notices.

**Comment by marcovtwout** [comment]
@ezyang Since https://github.com/ezyang/htmlpurifier/pull/310 was merged this issue can be closed. And could you please tag a new release so HTMLPurifier has PHP 8.1 support?

**Comment by mashb1t** [comment]
@ezyang which topics do still need to be finished until a new release can be created and can we support on that?

**Comment by ezyang** [comment]
just need me to find some time

**Comment by mashb1t** [comment]
@ezyang what is your rough estimate when you'll find the time to do the release? Currently this blocks the Yii1 compatibility PR for PHP8.1 compatibility https://github.com/yiisoft/yii/pull/4386 which would allow us as a business to add basically one more year of PHP support for our customers.
We as a business would highly appreciate to upgrade our Yii1 version at the start of next week including this fix.

**Comment by bytestream** [comment]
@mashb1t there is nothing stopping you from forking the lib temporarily and coming back when a release is done. Open source doesn't have time requirements.

**Comment by mashb1t** [comment]
@bytestream yes of course, thank you for mentioning this alternative. This is in fact another option but as far as i understood only a release/version tag is missing for this htmlpurifier to be officially PHP8.1 compatible to not break minimum stability requirements and having to fork both the yii1 framework repo and the htmlpurifier repo.

**Comment by mashb1t** [comment]
@ezyang is there any chance you find the time to create a new release in the next 2 weeks?

**Comment by c-schmitz** [comment]
Yes, please release.

**Comment by ezyang** [comment]
it turns out baby life makes you very very lazy

**Comment by marcovtwout** [comment]
@ezyang Could you let me know if you plan to release it within the next 2-3 weeks? Otherwise I will use a development version for the next Yii 1 release. Thanks!

**Comment by pszalko** [comment]
@ezyang Will you be able to release a version with PHP 8.1 support anytime soon? Thanks!
