### ISSUE TITLE
PHP 8.2 deprecated function utf8_decode , utf8_encode 

### ISSUE THREAD

**Issue by kitrio** [ezyang/htmlpurifier#320]
PHP 8.2 deprecated utf8_decode , utf8_encode  and remove in PHP 9.0
https://wiki.php.net/rfc/remove_utf8_decode_and_utf8_encode

utf8_encode function is ISO-8859-1 -> UTF8
utf8_decode function is  UTF8 -> ISO-8859

~~so alternative function is iconv~~  <- it's worng

**Comment by SharkMachine** [comment]
@Daijobou `mb_convert_encoding` can be used, but then mbstring extension will be an additional requirement.

**Comment by SharkMachine** [comment]
The goal of my PR was to get rid of `utf8_encode` and `utf8_decode` without breaking changes, which is why `symfony/polyfill-php72` was included

**Comment by SharkMachine** [comment]
@Daijobou It's also not that simple https://github.com/ezyang/htmlpurifier/pull/324#issuecomment-1190515412, I already tried it
