### ISSUE TITLE
Php 8.2

### ISSUE THREAD

**Issue by oleibman** [ezyang/htmlpurifier#334]
Now that Php8.2 has reached RC stage, and now that your code seems to be ready for it, what are your plans for a formal release of your package (changes that support 8.2 are not in the version available through Composer)?

**Comment by ezyang** [comment]
i'm on a business trip next week and might have time to do it then

**Comment by TimWolla** [comment]
@oleibman It appears that there are 3 tests remaining that are not entirely clean, see #335.

**Comment by ziegenberg** [comment]
Looking forward to the next release for PHP 8.2. Would love [to update this issue](https://tracker.moodle.org/browse/MDL-74823) and include the next release into Moodle.

**Comment by ezyang** [comment]
released

**Comment by oleibman** [comment]
Thank you - looks good!
