### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Gazoo** [ezyang/htmlpurifier#342]
I'm just a bit confused about the versioning. When I download the v4.16.0 tag all the code still references 4.15?

https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier.php#L61

Is this just a matter of forgetting to update the code or is there a reason for this?

**Comment by bytestream** [comment]
v4.16.0 is the same as v4.15.0. The release method changed and a bug meant that the versions specified in the code wasn't updated.

**Comment by Gazoo** [comment]
@bytestream Thanks for clearing things up for me :)
