### ISSUE TITLE
Version 16 have no differences to version 15?

### ISSUE THREAD

**Issue by Daijobou** [ezyang/htmlpurifier#344]
On website http://htmlpurifier.org/download is still only version 15 and file "VERSION" in version 16 (https://github.com/ezyang/htmlpurifier/releases/tag/v4.16.0) said "4.15.0"

I have compare v15 with v16 and for folder library there are no differences. Is v16 maybe a mistake?

**Comment by bytestream** [comment]
See https://github.com/ezyang/htmlpurifier/issues/342#issuecomment-1265201010

**Comment by Daijobou** [comment]
Why a new version if no changes are included and then why no fix of the version number with 4.16.1? ^^ I close this, but I do not understand it.
