### ISSUE TITLE
Is it possible to put a div inside an anchor tag?

### ISSUE THREAD

**Issue by mathsgod** [ezyang/htmlpurifier#368]
When purifier a div tag inside a tag, output is not my expected. HTML5 show be allow <a> tag to be wrapped around a <div> element.

Source:
```html
<a href="www.example.com">        
    <div> this is a link </div>
</a>
```
Output:
```html
<a href="www.example.com">        
    </a><div><a href="www.example.com"> this is a link </a></div><a href="www.example.com">
</a>
```

<a href="http://htmlpurifier.org/demo.php?filter%5BAutoFormat.AutoParagraph%5D=0&filter%5BAutoFormat.DisplayLinkURI%5D=0&filter%5BAutoFormat.Linkify%5D=0&filter%5BAutoFormat.RemoveEmpty.Predicate%5D=colgroup%3A%0D%0Ath%3A%0D%0Atd%3A%0D%0Aiframe%3Asrc%0D%0A&filter%5BAutoFormat.RemoveEmpty%5D=0&filter%5BAutoFormat.RemoveSpansWithoutAttributes%5D=0&filter%5BNull_CSS.AllowedProperties%5D=1&filter%5BCore.CollectErrors%5D=0&filter%5BNull_HTML.Allowed%5D=1&filter%5BNull_HTML.Doctype%5D=1&filter%5BHTML.SafeObject%5D=0&filter%5BHTML.TidyLevel%5D=medium&filter%5BURI.DisableExternalResources%5D=0&filter%5BNull_URI.Munge%5D=1&html=%3Ca+href%3D%22www.example.com%22%3E++++++++%0D%0A++++%3Cdiv%3E+this+is+a+link+%3C%2Fdiv%3E%0D%0A%3C%2Fa%3E&submit=Submit">Preview</a>

**Comment by bytestream** [comment]
This package doesn't support HTML5. You'll need to use xemlock/htmlpurifier-html5

**Comment by mathsgod** [comment]
Thanks.
