### ISSUE TITLE
javascript in a href if set with &colon;

### ISSUE THREAD

**Issue by joebordes** [ezyang/htmlpurifier#369]
`<a href="javascript:alert(document.domain)">XSShref1</a>`

gets sanitized to

`<a>XSShref1</a>`

but

`<a href="javascript&colon;alert(document.domain)">XSShref2</a>`

is left unmodified. Is that the expected behaviour of the library?

**Comment by ezyang** [comment]
To be clear, it is not left unmodified: the `&colon;` is converted to `&amp;colon;` The result is a valid URL to a local file named `javascript&colon;alert(document.domain)`, all of which is legal. Do you have a browser which is actually interpreting this as JavaScript?
