### ISSUE TITLE
Absolute worst security advice

### ISSUE THREAD

**Issue by CoderJoeW** [ezyang/htmlpurifier#371]
Just did a composer install ran the basic commands and got this in my error log

Directory /var/www/xxxxx/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 in /var/www/xxxxx/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php

1. Dont ever tell people to 777 horrible advice
2. Why is this package broken straight out of the box?

Using php 8.2

**Comment by pyres01** [comment]
邮件已收到，谢谢！
