### ISSUE TITLE
Allow commas in tel URIs

### ISSUE THREAD

**Issue by danbrellis** [ezyang/htmlpurifier#388]
At least here in the U.S., dialing a comma in a phone number indicates a puase of a few seconds. As a result, often video conference call-in numbers will include a comma in the dial-in number before the passcode to save the caller from having to dial in the passcode separately.

However, the current implementation of the [tel URIScheme](https://github.com/ezyang/htmlpurifier/blob/master/library/HTMLPurifier/URIScheme/tel.php#L38-L40) strips out everything other than numbers, `x`, and a leading `+`. Thus:

`<a href="tel:+12029910477,,32288696#">+1 202-991-0477,,32288696#</a>`

is formatted to 

`<a href="tel:+1202991047732288696#">+1 202-991-0477,,32288696#</a>`

which results in a  wrong number dialed.

Does it make sense to allow commas in numbers? And/or can someone advise on how to override that regex?

**Comment by ezyang** [comment]
Sure, send a patch.

**Comment by danbrellis** [comment]
Thanks @ezyang - PR #389 created!
