### ISSUE TITLE
`DirectLex` will cause PHP error 

### ISSUE THREAD

**Issue by lenhatthanh20** [ezyang/htmlpurifier#393]
https://github.com/ezyang/htmlpurifier/blob/bbc513d79acf6691fa9cf10f192c90dd2957f18c/library/HTMLPurifier/Token/Tag.php#L47

Hello, 
When I use HTML Purifier with `Core.LexerImpl = DirectLex`, The PHP error will cause in above line when I purify the below data:
`<a href="https://example.com/" 10="hoge">Test</a>`
Because the key of attribute is `non-string` value. So the PHP error will be occured.
Ref: https://www.php.net/manual/en/function.ctype-lower.php

Please help to fix it.
I think we can fix it by using quick typecast in the `Tag.php` file:
`$key = (string)$key;` 

Or remove the attribute if the key is non-string value.

Thank you so much

**Comment by bytestream** [comment]
What is the value of `$attr` and `$key` if you dump the values? It's perhaps something to do with `10` not being a valid attribute name.

**Comment by lenhatthanh20** [comment]
In my example, the attribute key is `10` and the value is `hoge`. I know the attribute key `10` is invalid because it is a `non-string`. 
But my expected is:
- Output: `<a href="https://example.com/">Test</a>` (remove invalid attribute `10`)
- There is no PHP error or warning.

**Comment by matsuo** [comment]
Resolved with https://github.com/ezyang/htmlpurifier/releases/tag/v4.18.0.
