### ISSUE TITLE
The behavior for blank node parsing changed in later versions of PHP.

### ISSUE THREAD

**Issue by charlie-curtis** [ezyang/htmlpurifier#403]
### Description
When upgrading from PHP8.1.22 to PHP8.3.4, there is inconsistent output between versions -- specifically for how blank nodes are handled.

### Example

**Input**
```html
<table>
	<caption>
		Cool table
	</caption>
	<tfoot>
	<tr>
		<th>I can do so much!</th>
	</tr>
	</tfoot>
	<tr>
		<td style="font-size:16pt;
      color:#F00;font-family:sans-serif;
      text-align:center;">Wow</td>
	</tr>
</table>
```

**PHP8.1.22 output**
```html
<table><caption>
		Cool table
	</caption>
	<tfoot><tr><th>I can do so much!</th>
	</tr></tfoot><tr><td style="font-size:16pt;color:#F00;font-family:sans-serif;text-align:center;">Wow</td>
	</tr></table>
```

**PHP8.3.4 output**
```html
<table>
	<caption>
		Cool table
	</caption>
	<tfoot>
	<tr>
		<th>I can do so much!</th>
	</tr>
	</tfoot>
	<tr>
		<td style="font-size:16pt;color:#F00;font-family:sans-serif;text-align:center;">Wow</td>
	</tr>
</table>
```

### Impact
A strong case can be made that the PHP8.3.4 output is "more correct", and I wouldn't argue. The issue is that there is a ton of existing code and applications that maybe relying on the old behavior in order to "work". Having an optional backwards-compatible solution would ease the transition as many upgrade beyond PHP8.1.

### Investigation
These steps have been performed:
- verified that both PHP versions used for testing have the same version of libxml (2.9.1)
- localized the behavior change to the `loadHtml` call [here](https://github.com/ezyang/htmlpurifier/blob/909dda6621cf06eb5ac1ea80955306c818d7122f/library/HTMLPurifier/Lexer/DOMLex.php#L79-L81)
- verified that passing the `LIBXML_NOBLANKS` option fixed the output discrepancy

I think [this](https://github.com/php/php-src/commit/c283c3ab0ba45d21b2b8745c1f9c7cbfe771c975#diff-3c2cd6479b2be10875c7be2f2fcce5263d5efc342062ed6632a9a0354c7bd19bR153) php-src commit changed the default behavior of "blank" parsing from "don't keep" to "keep".

### Suggested Fix
Much like `LIBXML_PARSEHUGE` is an _optional_ configuration value that can be supplied [here](https://github.com/ezyang/htmlpurifier/blob/909dda6621cf06eb5ac1ea80955306c818d7122f/library/HTMLPurifier/Lexer/DOMLex.php#L72-L74), I propose adding `LIBXML_NOBLANKS` as an optional value in order to better handle backwards compatibility as mentioned above without impacting existing use cases.

### Similar issues

https://github.com/ezyang/htmlpurifier/issues/237
https://github.com/ezyang/htmlpurifier/issues/269

**Comment by ezyang** [comment]
Sgtm send the pr

**Comment by charlie-curtis** [comment]
@ezyang thanks, the PR is here: https://github.com/ezyang/htmlpurifier/pull/404
