### ISSUE TITLE
Config Core.AllowHostnameUnderscore work incorrectly

### ISSUE THREAD

**Issue by lenhatthanh20** [ezyang/htmlpurifier#405]
Hello, 

Im try to using the config Core.AllowHostnameUnderscore to allow underscore (_) in the hostname.
Ref: http://htmlpurifier.org/live/configdoc/plain.html#Core.AllowHostnameUnderscore
But it works incorrectly in some cases.

For example: 
- This URL will work: https://ex_mple.com/foo/bar
- This URL will not work: http://example_.com/foo/bar
- This URL will not work: http://_sip._udp.apnic.net

Do you have any alternative solution for this issue?

Thank you.

**Comment by matsuo** [comment]
Resolved with https://github.com/ezyang/htmlpurifier/releases/tag/v4.18.0.
