### ISSUE TITLE
Support for iframe.allowfullscreen attribute

### ISSUE THREAD

**Issue by zerocrates** [ezyang/htmlpurifier#409]
HTMLPurifier knows about support for allowing fullscreen for objects/Flash, but not iframes.

Is there interest/appetite in adding this for iframes? It's in the standard, and is very common in embed codes of the type that might be expected to be allowed by SafeIframe.

I'd be happy to send a PR if there's a sense this would be accepted. Possibly behind a setting like HTML.Trusted, or a specific one for this alone?

**Comment by ezyang** [comment]
Feel free to chuck whatever you want in Trusted.
