### ISSUE TITLE
php 8.3

### ISSUE THREAD

**Issue by mimooh** [ezyang/htmlpurifier#416]
Hi, ubuntu 24.04 uses php8.3, but htmlpurifier supports up to php8.1 and I'm in trouble after my server got upgraded yesterday. Is 8.3 support planned?

**Comment by joebordes** [comment]
I am using htmlpurifier on 8.3 with no issues.
What error are you seeing?

**Comment by bytestream** [comment]
@mimooh you need to update ezyang/htmlpurifier to 4.17.0. PHP 8.3 is not supported on v4.16.0 which you have installed. 

This issue should be closed.

**Comment by mimooh** [comment]
php /usr/local/bin/composer -W require ezyang/htmlpurifier --ignore-platform-reqs
fixes my issue, thank you!
