### ISSUE TITLE
PHP 8.4 support

### ISSUE THREAD

**Issue by cracksalad** [ezyang/htmlpurifier#417]
As I have seen, you already added PHP 8.4 to the set of allowed versions in the composer.json, but there is no release right now. Does this mean that it is not yet compatible or are you just waiting until PHP 8.4 is finally released? 
Since the first RC of PHP 8.4 is out now, I think we can be sure, that there will not be any major changes until the final release. An update to this project allowing the usage of PHP 8.4 would help dependents to test their projects with 8.4.

**Comment by pyres01** [comment]
邮件已收到，谢谢！

**Comment by DoobleD** [comment]
Interested with this as well!

**Comment by TimWolla** [comment]
Resolved with https://github.com/ezyang/htmlpurifier/releases/tag/v4.18.0.
