### ISSUE TITLE
htmlpurifier standalone for composer

### ISSUE THREAD

**Issue by kamov** [ezyang/htmlpurifier#43]
Hi

I would like to use htmlpurifier standalone with  composer, how to do ?

The example show only wtih full library.

thanks

**Comment by dmyers** [comment]
Have you tried adding `ezyang/htmlpurifier:dev-master` to your composer.json file?

**Comment by FractalizeR** [comment]
I believe 4.6 stable version must be used, not dev-master.

**Comment by ezyang** [comment]
Hello guys, what, if anything, should I do about this bug?

**Comment by FractalizeR** [comment]
I don't think there is much to do ;) composer works flawlessly with htmlpurifier repo.
