### ISSUE TITLE
Links with dashes in domain gets messed up big time when linkifying 

### ISSUE THREAD

**Issue by maktouch** [ezyang/htmlpurifier#47]
Normal dashes in domain is okay, but there's specific pattern where it doesn't work

http://subdomain-.domain.com/first/second.html

That's unfortunately a valid domain. When linkifying is enabled, it it becomes

```
<a href="/first/second.html">http://subdomain-.domain.com/first/second.html</a>
```

This works okay though:
http://sub-domain.domain.com/first/second.html

**Comment by summerblue** [comment]
@maktouch How can you solve this problem?
