### ISSUE TITLE
It cuts not tags also. 

### ISSUE THREAD

**Issue by RusAlex** [ezyang/htmlpurifier#50]
I already wrote to the mailling list. But I think better to do it here also.

```php
    $config = HTMLPurifier_Config::createDefault();
    $config->set('HTML.Allowed', '');
    $p = new HTMLPurifier($config);
    $p->purify('L<R blabla'); 
```

result is "L" just "L" letter.

Is it correct behavior ?

**Comment by ezyang** [comment]
It's how browser interpret it, so yes, I think so.
