### ISSUE TITLE
Docs: Composer install

### ISSUE THREAD

**Issue by mryellow** [ezyang/htmlpurifier#54]
Composer install option is missing from docs.

http://htmlpurifier.org/download#PEAR

**Comment by ezyang** [comment]
What kind of text would you like to see here? Is a simple link to the Packageist listing OK? Is there some standard composer boilerplate? (Asking because I don't use composer.)

**Comment by mryellow** [comment]
Maybe just a `composer require ezyang/htmlpurifier` somewhere.

I'm kinda new to composer so took a second to think I could find it myself.

**Comment by ezyang** [comment]
OK, I added a short little stub about it.
