### ISSUE TITLE
'flashvars' check is case sensitive

### ISSUE THREAD

**Issue by ProfessorBeekums** [ezyang/htmlpurifier#57]
HTMLPurifier_Injector_SafeObject has a variable called "$allowedParam" that is used to filter out some tokens in a flash object. Currently this does a case sensitive check on "flashvars" but other variations such as "FlashVars" are filtered out. Given that Adobe uses "FlashVars" in it's example, this should probably be a case insensitive check.

I can make the changes and generate a pull request, but I'm curious. Should all checks against "$allowedParam" be case insensitive or is it better to just add "FlashVars" to the array?

**Comment by ezyang** [comment]
Or we could normalize it to lower case, like we do for everything else.
