### ISSUE TITLE
Please tag a new stable version of the library

### ISSUE THREAD

**Issue by stof** [ezyang/htmlpurifier#61]
The latest release has been done in 2013. This means that people using Composer with its default settings (allowing only stable versions of packages) will not benefit from any of the bug fixes done since then. I just discovered that a bug annoying me all the time (https://github.com/ezyang/htmlpurifier/issues/32) has been fixed 6 months ago, but I don't have the fix because it is not released yet.

**Comment by ezyang** [comment]
Done.

**Comment by stof** [comment]
thanks
