### ISSUE TITLE
Bug: HTML tag in comment taken as root element

### ISSUE THREAD

**Issue by luksurious** [ezyang/htmlpurifier#67]
Take the following snippet:

```
<p>Text</p>
<!-- <html><body>Commented</body></html> -->
```

HTMLPurifier returns `Commented` as the cleaned result, which is wrong. It should return `Text`

Demo: http://htmlpurifier.org/demo.php?filter%5BAutoFormat.AutoParagraph%5D=0&filter%5BAutoFormat.DisplayLinkURI%5D=0&filter%5BAutoFormat.Linkify%5D=0&filter%5BAutoFormat.RemoveEmpty%5D=0&filter%5BAutoFormat.RemoveSpansWithoutAttributes%5D=0&filter%5BNull_CSS.AllowedProperties%5D=1&filter%5BCore.CollectErrors%5D=0&filter%5BNull_HTML.Allowed%5D=1&filter%5BNull_HTML.Doctype%5D=1&filter%5BHTML.SafeObject%5D=0&filter%5BHTML.TidyLevel%5D=medium&filter%5BURI.DisableExternalResources%5D=0&filter%5BNull_URI.Munge%5D=1&html=%3Cp%3EText%3C%2Fp%3E%0D%0A%3C%21--+%3Chtml%3E%3Cbody%3ECommented%3C%2Fbody%3E%3C%2Fhtml%3E+--%3E&submit=Submit

**Comment by ezyang** [comment]
As a workaround, assuming you don't need the extraction behavior, you can set %Core.ConvertDocumentToFragment to false.
