### ISSUE TITLE
IDs starting with numbers disallowed, even with Attr.EnableID = true

### ISSUE THREAD

**Issue by olemartinorg** [ezyang/htmlpurifier#73]
Hi!

I stumbled upon this problem with numeric id attributes (or at least id attributes that starts with numbers). They are stripped out, even if I turn Attr.EnableID on.

See this example:
```php
$config = HTMLPurifier_Config::createDefault();
$config->set('Attr.EnableID', true);
$purifier = new HTMLPurifier($config);

var_dump(
    $purifier->purify('<div id="helloWorld"></div>'),
    $purifier->purify('<div id="4-helloWorld"></div>'),
    $purifier->purify('<div id="5"></div>'),
    $purifier->purify('<div id="a6"></div>')
);
```

The output is:
```
string '<div id="helloWorld"></div>' (length=27)
string '<div></div>' (length=11)
string '<div></div>' (length=11)
string '<div id="a6"></div>' (length=19)
```

**Comment by ezyang** [comment]
HTML Purifier is still in the HTML 4 regime, where IDs with leading numbers are forbidden. We'd need an HTML 5 mode to loosen this restriction.

**Comment by olemartinorg** [comment]
I take it that won't be introduced any time soon? This was apparently very important for some of our users, so I'll have to make a workaround in my wrapping code, then.

**Comment by olemartinorg** [comment]
Hooray! Thanks, @ezyang! I don't see the 4.8.0 release on packagist yet, is that something you'll have to update manually?

**Comment by ezyang** [comment]
Uh, I have no idea how to update the packagist listing haha.

**Comment by olemartinorg** [comment]
Allright, I'll just wait and see! :-) Thanks again!
