### ISSUE TITLE
How to use htmlpurifer in Laravel 5

### ISSUE THREAD

**Issue by euclid1990** [ezyang/htmlpurifier#75]
In **Laravel 5**, To use this library, I have to install it via composer: All library files is put in `project_folder/vendor/ezyang/htmlpurifier/library/HTMLPurifier.auto.php`
And use below command in each class:
```
require_once app_path() . '/../vendor/ezyang/htmlpurifier/library/HTMLPurifier.auto.php';
```
Have a better than this way ?

Thank you !

Note: app_path() function return: `project_folder/app`
My web struct:
```
-- project_folder
---- app
---- vendor
-------- ezyang
------------ ...
```

**Comment by mbeech** [comment]
Take a look at https://github.com/mewebstudio/Purifier

**Comment by ezyang** [comment]
Closing this as not a bug in core HTML Purifier.

**Comment by chenwenbo123** [comment]
thanks
