### ISSUE TITLE
Core.EnableIDNA without PEAR Net_IDNA2

### ISSUE THREAD

**Issue by althaus** [ezyang/htmlpurifier#77]
Hey,

we just stumbled upon an issue with international domain names. As they are getting more and more common (especially in Germany with our umlauts) I found out that HTMLPurifier "kills" those in the purification process. We developing a deployable system running on 1000+ Debian servers and don't want to add PEAR dependencies. As the code of `HTMLPurifier/AttrDef/URI/Host.php` is based on 2012 PHP I'd kindly ask, if it'd be possible to update that one with proper support of the php_intl component, which offers built-in functions for IDNs: http://php.net/manual/ref.intl.idn.php

As far as I understood the Net_IDNA2 usage the idn_to_x functions should be a proper replacement?

Cheers
Matthias

**Comment by ezyang** [comment]
OK fixed in https://github.com/ezyang/htmlpurifier/commit/aebe1c02a2eb2f5135f7a9806059dc5d7f8e64d6

**Comment by althaus** [comment]
Many thanks for the quick implementation. I'm looking forward for a new release and will use master so long.

:+1:
