### ISSUE TITLE
Missing spaces after upgrade from 4.6.0 to 4.7.0

### ISSUE THREAD

**Issue by fieg** [ezyang/htmlpurifier#78]
On 4.6.0 we had the following:

```
<b>Vetgedrukt</b> <i>Schuingedrukt</i> <span>Hou</span><iframe></iframe><script></script> jij ook zo van vakjesdenken?
```

became:

```
<b>Vetgedrukt</b> <i>Schuingedrukt</i> Hou jij ook zo van vakjesdenken?
```

since 4.7.0 it becomes:

```
<b>Vetgedrukt</b><i>Schuingedrukt</i>Hou jij ook zo van vakjesdenken?
```

I checked the changeset (https://github.com/ezyang/htmlpurifier/compare/v4.6.0...v4.7.0) but can't really find what's causing this.

Any thoughts?

**Comment by ezyang** [comment]
Just to confirm, when you revert to v4.6.0 the problem goes away?

**Comment by fieg** [comment]
Yes, when I revert to v4.6.0 the problem does not appear.

**Comment by ezyang** [comment]
Are you using Composer by any chance?

**Comment by fieg** [comment]
Yes.

**Comment by ezyang** [comment]
I can't reproduce the behavior you're reporting on 4.7.0. Your best bet might be to bisect it yourself (there aren't that many commits between 4.6.0 and 4.7.0 and report back here.) Alternately, tell us what version of PHP and libxml you have, and whether or not the dom extension is enabled.

**Comment by jamslater** [comment]
I'm experiencing the same issue and have narrowed it down to commit 15d1a3003a516f46b3f253747c116ffc830e1d9c which removed the `<div>` wrapper around the HTML.

So far I have tested with libxml2 2.7.6 and 2.9.1 with the same result.

**Comment by jamslater** [comment]
This only occurs with the `HTML 4.01 Strict` doctype, the others are fine.

@fieg is that what you are/were using?

**Comment by fieg** [comment]
I don't know, it's a while back and don't have the use case at hand anymore.

**Comment by ezyang** [comment]
@jamslater OK, so probably what is happening is that on some versions of libxml, whitespace is treated differently depending on whether or not we are parsing inside a body or a div. FWIW, the version of libxml I've been testing against is 2.9.4. I'll see if I can find a 2.9.1 copy lying around somewhere...

**Comment by ezyang** [comment]
Yes! Repro [here](http://htmlpurifier.org/demo.php?filter%5BAutoFormat.AutoParagraph%5D=0&filter%5BAutoFormat.DisplayLinkURI%5D=0&filter%5BAutoFormat.Linkify%5D=0&filter%5BAutoFormat.RemoveEmpty.Predicate%5D=colgroup%3A%0D%0Ath%3A%0D%0Atd%3A%0D%0Aiframe%3Asrc%0D%0A&filter%5BAutoFormat.RemoveEmpty%5D=0&filter%5BAutoFormat.RemoveSpansWithoutAttributes%5D=0&filter%5BNull_CSS.AllowedProperties%5D=1&filter%5BCore.CollectErrors%5D=0&filter%5BNull_HTML.Allowed%5D=1&filter%5BHTML.Doctype%5D=HTML+4.01+Strict&filter%5BHTML.SafeObject%5D=0&filter%5BHTML.TidyLevel%5D=medium&filter%5BURI.DisableExternalResources%5D=0&filter%5BNull_URI.Munge%5D=1&html=%3Cb%3Ea%3C%2Fb%3E+%3Ci%3Eb%3C%2Fi%3E&submit=Submit).
