### ISSUE TITLE
HTMLPurifier causes segmentation fault

### ISSUE THREAD

**Issue by zengxiaoluan** [ezyang/htmlpurifier#79]
this is my code:

include_once 'htmlpurifier/HTMLPurifier.auto.php';
$config = HTMLPurifier_Config::createDefault();
$purifier = new HTMLPurifier($config);
$html = $purifier->purify($html);

if the $html = 'a very long rich html text more than ten thousand character' ,it will cause segmentation fault.

**Comment by ezyang** [comment]
What version of PHP on what OS? Does $purifier->purify(str_repeat("a", 12000)) segfault?

**Comment by zengxiaoluan** [comment]
My php version is 'PHP 5.4.16 (cli) (built: Jun 23 2015 21:17:27)';

My OS is ‘Linux version 3.10.0-123.9.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Thu Nov 6 15:06:03 UTC 2014’

and  I tested $purifier->purify(str_repeat("a", 12000)) ,not segfault.

**Comment by ezyang** [comment]
I don't know if you can upload the HTML text somewhere. If you can that would make debugging a lot easier.

**Comment by zengxiaoluan** [comment]
that is the HTML text:
三千院风，dota官网版主、dota吧吧主，微信号最dotaer
唐嘉文、冬瓜、Song Jimmy 等人赞同 等人赞同
<p>是不是良心制作人，需要历史地去看待问题：</p><p>2005年左右，IF从6.10开始接手Dota Allstars。十年多了，各大对战平台靠DotA赚得盆满钵满，冰蛙却没有靠更新DotA挣过一分钱。DotA快速成长为最受欢迎的War3地图，强行为War3平台续命多年。然而直到DOTA2问世前，作者都没有通过自己的作品获得任何收益。这是冰蛙受人膜拜的原因之一，不求回报的长年奉献。</p><p>有人无视风杖，说自己才是DotA的最初作者，没有自己就不会有DotA,这里不点名批评一下放弃DotA去挣外快的羊刀同学。然而DotA最终之所以成为DotA，并不是因为一两个创意，或者一个bug频出的地图，而是IF长期以来精益求精的制作和更新。</p><p>IF将不朽盾从商店移到Roshan身上，重制了鸡肋的神杖，限制了IMBA的跳刀，魔瓶创造出控符这一概念，重做了小狗等多个只在路人局才有意义的大后期英雄，改变龙心的回血方式，移除血精的回血属性，甚至连随地乱扔的树枝都有了欢乐的主动技能。可以说，无数类似的改动，都能看出IF无处不在的用心。精益求精的匠人精神，这是冰蛙受人膜拜的原因之二。</p><p>DotA在芸芸的地图海洋中拼杀出来，成为最受欢迎的地图，拥有上千万的粉丝。在没有制作公司支撑的情况下，各地自主举办了多个赛事，诞生出许多古老的职业大神。一个人耐得住寂寞，已经令人敬佩；而耐得住这样的成功，除了冰蛙可谓少之又少。</p><p>我如果处在IF的位置上，恐怕早就尾巴翘到天上去了：去各地巡回演讲，给的少了都不干；把自己照片贴满大街小巷，连厕所门后也不放过；卖卖肉松饼，和女粉丝谈下人生理想；在各大赛事、会议讲话，不管懂不懂，谈谈最时髦的互联网和游戏概念；直播吃饭、喝水、睡觉，推出付费英雄、花钱买属性，怎么捞钱怎么来。</p><p>然而直到现在，我们还是不知道冰蛙的照片和名字。冰蛙呕心沥血缔造出的DOTA2，第一届邀请赛时他也只是去现场低调地看了看，没有玩家和选手认识他。能够低调谦逊务实刻苦到这个境界，想不让别人献上自己的膝盖也难啊！</p><p>不求回报的长年奉献、精益求精的匠心精神、低调务实的人生态度，能够做到这三点的人，你告诉我他是不是良心制作人？</p> <span class="answer-date-link-wrap"> <a class="answer-date-link last_updated meta-item" data-tip="s$t$发布于 昨天 11:08" target="_blank" href="/question/41274993/answer/90356847">编辑于 12:00</a> </span>
是不是良心制作人，需要历史地去看待问题：2005年左右，IF从6.10开始接手Dota Allstars。十年多了，各大对战平台靠DotA赚得盆满钵满，冰蛙却没有靠更新DotA挣过一分钱。DotA快速成长为最受欢迎的War3地图，强行为War3平台续命多年。然而直到DOTA2问世前，作… 显示全部
关注问题关注问题143 条评论感谢分享收藏•没有帮助•举报•作者保留权利收起 
https://www.zhihu.com/#
此内容将不会在动态中再次显示 •撤销https://www.zhihu.com/#

家居

来自 家居
有哪些漂亮又好养的植物？
家里楼顶打算打造一个小花园，有哪些是比较...  显示问题详情
家里楼顶打算打造一个小花园，有哪些是比较耐养而且好看的植物，各位给些建议！ ps楼主南方地区，室内室外都可以，室内也缺植物装饰
657657
657赞同反对，不会显示你的姓名
喵少行状录，啰嗦理工女/腐国海龟/脑洞补不上啊！
就是那个路过的人、光脚丫、周里里 等人赞同 等人赞同
<b>感谢大家这么支持一个业余种植物的。<br></b><b>北京，天蓝，风大。</b><br><b>携众植物晒太阳，向跟大家问安！</b><br>----2016.03.13 update<br><img data-rawwidth="1242" data-rawheight="1535" src="https://pic2.zhimg.com/d14c93e877cab4147fb83861898e78b9_b.jpeg" class="origin_image zh-lightbox-thumb" width="1242" data-original="https://pic2.zhimg.com/d14c93e877cab4147fb83861898e78b9_r.jpeg"><br><br><br>【以下原文】<br>推荐些自己养的<b>室内植物</b>，<b>全部自养，全部原创（多图）供大家参考。爱植物的你们长得一定很好看！多点赞鼓励啊！</b>本人坐标北京，一般上班族，养植物，那必须是要经得起北方气候和人为摧残！<b>照顾方式属于不专业、粗暴型。虽然也爱尝试些新物种，但也基本上都是大普货！不心疼啊啊啊～ </b>家里有花有植物，真的感觉很有格调，幸福感提升得棒棒哒！<br><br>多图预警，以下植物们，有不用照顾就活的天长地久的；也有新入本人魔爪，还不知道能坚持多久的植物，未来会持续跟进，推荐心得。（ps. 回头可以把养死的植物也做一专篇，科科）<br>——————————————————<br><b>正文开始</b><br><b><br>No.1 仙人掌（具体名字，忘了）<br></b><b>饲养时长：一年半<br>生存指数：5颗星</b><br><b>暴力照顾：不用浇水，干着。<br></b><br>配个好看的小盆就这样摆在搁板上，就很完美了！⬇️<br><img data-rawwidth="3264" data-rawheight="2448" src="https://pic3.zhimg.com/f4e948f19af7a73cfbe2b9bc96b381a2_b.jpeg" class="origin_image zh-lightbox-thumb" width="3264" data-original="https://pic3.zhimg.com/f4e948f19af7a73cfbe2b9bc96b381a2_r.jpeg"><br>放大看是这样的，是不是很像小猴子的尾巴？萌萌的，当时好像大概价格也就五元一盆的甩卖，炒鸡划算。⬇️<br><img data-rawwidth="2448" data-rawheight="2448" src="https://pic1.zhimg.com/336b74f6da3fe5f09b76bf8f1cade200_b.jpeg" class="origin_image zh-lightbox-thumb" width="2448" data-original="https://pic1.zhimg.com/336b74f6da3fe5f09b76bf8f1cade200_r.jpeg"><br><b>No.2 富贵竹 （喜欢风水的朋友你们懂的！每年放在恰当位置上催旺事业学业的，居家必备植物！）</b><br><b>饲养时长：两年多<br>生存指数：5颗星<br>暴力照顾：水培，完全不照顾</b><b>，</b><b>一年添加几次水就可以。</b><br><img data-rawwidth="2435" data-rawheight="2435" src="https://pic2.zhimg.com/14dced341b3e53d2dbd02640b13c0a69_b.jpeg" class="origin_image zh-lightbox-thumb" width="2435" data-original="https://pic2.zhimg.com/14dced341b3e53d2dbd02640b13c0a69_r.jpeg"><br><b>No.3 幸福树（逛宜家时候买的，桃红花盆也是）饲养时长：一年半</b><br><b>生存指数：5颗星</b><br><b>暴力照顾：一礼拜浇透一次，黄了把叶子剪掉，反正长的很快。</b><br><br><img data-rawwidth="2123" data-rawheight="2123" src="https://pic4.zhimg.com/a059da8c949d47cbabfa8372a68095cb_b.jpeg" class="origin_image zh-lightbox-thumb" width="2123" data-original="https://pic4.zhimg.com/a059da8c949d47cbabfa8372a68095cb_r.jpeg"><br><b>No.4 薄荷</b><b><br>饲养时长：一年<br>生存指数：超5颗星<br>暴力照顾：必须水栽！除非你做好天天浇水的准备。多晒太阳，促进生根。</b><br><br>一开始我也是薄荷放土里养，发现老干死，怎么都养不好。后来死的只剩一根枝条了，于是丢到玻璃瓶里搁水养着，很快就长出根还越长越多，现在都分出三小瓶了！生命力及其顽强，而且桌面装饰太好看了。心情低落时用手指尖拨弄一下薄荷，再放到鼻子前嗅一嗅，真的很提神醒脑！<br><br>一开始放土里养的样子，因为老忘浇水，后来干死了⬇️<br><img data-rawwidth="2448" data-rawheight="2448" src="https://pic4.zhimg.com/9264d9653fa983d09edbc646ec26e593_b.jpeg" class="origin_image zh-lightbox-thumb" width="2448" data-original="https://pic4.zhimg.com/9264d9653fa983d09edbc646ec26e593_r.jpeg"><br>残存的一小段薄荷枝（无根），随便丢水瓶里，一个月后简直是满血复活！⬇️<br><img data-rawwidth="2999" data-rawheight="3557" src="https://pic2.zhimg.com/9ccbf6c88fa4e49ecf1a1317bc9ca4bd_b.jpeg" class="origin_image zh-lightbox-thumb" width="2999" data-original="https://pic2.zhimg.com/9ccbf6c88fa4e49ecf1a1317bc9ca4bd_r.jpeg"><br>分了一部分薄荷放床头柜上，效果杠杠的⬇️<br><img data-rawwidth="2448" data-rawheight="2448" src="https://pic2.zhimg.com/f699012c101e49594e59b25c780f6471_b.jpeg" class="origin_image zh-lightbox-thumb" width="2448" data-original="https://pic2.zhimg.com/f699012c101e49594e59b25c780f6471_r.jpeg"><br><b>No.5 多肉植物</b><br><b>饲养时长：一年<br>生存指数：3颗星<br>暴力照顾：晒着，不给水，心情好就给点喷雾。一个月浇透一次。最近学着偶尔给点营养液，不知道会不会长的好看些。</b><br><br>多肉最重要的多晒，少浇水！感觉一浇水就长残了。反正一年半的时间里，肉肉也就死了一株，所以我也归为“好养的植物”。 但是肉肉会徒长，长很高，只好砍头插枝；有些身材走样，变成大胖子，反正没有小时候萌了。。。。⬇️<br><br><img data-rawwidth="2448" data-rawheight="2448" src="https://pic2.zhimg.com/dec3be28f496bac9ac7f55634eeb49b1_b.jpeg" class="origin_image zh-lightbox-thumb" width="2448" data-original="https://pic2.zhimg.com/dec3be28f496bac9ac7f55634eeb49b1_r.jpeg"><br><img data-rawwidth="2448" data-rawheight="3059" src="https://pic1.zhimg.com/7ca3c0ca85a8a7bc80c9e81d0d35b64c_b.jpeg" class="origin_image zh-lightbox-thumb" width="2448" data-original="https://pic1.zhimg.com/7ca3c0ca85a8a7bc80c9e81d0d35b64c_r.jpeg"><br>现在已经长成大石头的肉肉⬇️和第一张还是小屁屁的样子已是相去甚远啊。<br><img data-rawwidth="2229" data-rawheight="2229" src="https://pic1.zhimg.com/9de087d809eb4ccae5fc09ae3adeb418_b.jpeg" class="origin_image zh-lightbox-thumb" width="2229" data-original="https://pic1.zhimg.com/9de087d809eb4ccae5fc09ae3adeb418_r.jpeg"><br><br><b>No.6 蝴蝶兰</b><b><br>饲养时长：半年<br>生存指数：4颗星<br>暴力照顾：两星期浇一次水，根据北京雾霾的频率，偶尔晒太阳。</b><br><br>这种优美且高逼格的花，强烈推荐。可以在<b>自己晒太阳喝茶的时候可以放身边一起补钙。</b>每次看到那优雅的花枝，都心情大好。最主要，花期很长，我在北京室内养，都能开3个多月，南方更不在话下。30元一盆，能开花这么久，很划算啊！！！花谢完后可以剪去长枝继续养着，新枝和花蕊长出来后还能再开。⬇️<br><br><img data-rawwidth="2448" data-rawheight="1836" src="https://pic1.zhimg.com/0ed08368492eccb9033daf1a068cd98c_b.jpeg" class="origin_image zh-lightbox-thumb" width="2448" data-original="https://pic1.zhimg.com/0ed08368492eccb9033daf1a068cd98c_r.jpeg"><br>剪下来的长枝可以插在玻璃水培容器上。花败了也没关系，有种残缺的美。⬇️<img data-rawwidth="2148" data-rawheight="2148" src="https://pic4.zhimg.com/6fd0a520e458a4b4d8fbab4ab2ac0453_b.jpeg" class="origin_image zh-lightbox-thumb" width="2148" data-original="https://pic4.zhimg.com/6fd0a520e458a4b4d8fbab4ab2ac0453_r.jpeg"><br><br><b>No.7 铜钱草（在大理、丽江民宿院子地上经常能看见这种草，绿油油生机勃勃，感觉很接地气，每次看到它总有种度假小资的感觉 ）</b><b><br>饲养时长：半年<br>生存指数：4颗星（持续观察）<br>暴力照顾：北京太干，必须水培。放在有光阴凉处，不用搭理。不要晒，晒了会蔫。</b><br><br>下图是土培没错，可北京太干，不想每天浇水 我把盆底的洞堵上了，往盆里灌满水，能支撑3-5天不干枯。⬇️<br><img data-rawwidth="2448" data-rawheight="2448" src="https://pic1.zhimg.com/632124cea9d86311a34fb0e87ede49fc_b.jpeg" class="origin_image zh-lightbox-thumb" width="2448" data-original="https://pic1.zhimg.com/632124cea9d86311a34fb0e87ede49fc_r.jpeg"><br>扯一小段带根枝，放在小白盆里做水培，试试看能不能长出一盆来。（以后再更新给大家成果）⬇️<br><img data-rawwidth="2335" data-rawheight="2335" src="https://pic1.zhimg.com/dc06e3be28bbcdc8fa405e187c71a12c_b.jpeg" class="origin_image zh-lightbox-thumb" width="2335" data-original="https://pic1.zhimg.com/dc06e3be28bbcdc8fa405e187c71a12c_r.jpeg"><br><b>No.8 芦荟</b><b><br>饲养时长：两个月<br>生存指数：4颗星（持续观察）<br>暴力照顾：放台面上，看书喝水的时候给点水即可。</b><br><br><br>南方常种植物，老妈非常喜欢，因为可以揪一小块下来擦手啊，烫伤伤口都好用。所以你也看到了，这芦荟长的，咳咳，被揪的都快没了。⬇️<br><img data-rawwidth="2253" data-rawheight="2253" src="https://pic2.zhimg.com/f90df1aa66d11cb125ff3cefaab6f931_b.jpeg" class="origin_image zh-lightbox-thumb" width="2253" data-original="https://pic2.zhimg.com/f90df1aa66d11cb125ff3cefaab6f931_r.jpeg"><br>做个小景，吃烛光晚餐有小猫陪伴，也不错噢⬇️<br><img data-rawwidth="3264" data-rawheight="2448" src="https://pic4.zhimg.com/b4ed9791e89c00c2c777f10683bf83ff_b.jpeg" class="origin_image zh-lightbox-thumb" width="3264" data-original="https://pic4.zhimg.com/b4ed9791e89c00c2c777f10683bf83ff_r.jpeg"><br><br><b>No.9 含羞草+苔藓</b><b><br>饲养时长：四个月<br>生存指数：3.5颗星（持续观察）<br>暴力照顾：放罐子里，封上保鲜膜，一礼拜喷喷水。</b><br><b>Tip：玻璃造景的植物，喷壶一定要用纯净水，因为用自来水过没多久玻璃周边全部都是水渍印。不能容忍！！！</b><br><br>含羞草很可爱，白天会打开像一把大伞一样把苔藓遮盖住，晚上就都合上睡觉了。苔藓也十分好养，只要你用保鲜膜盖着让水分保持在玻璃缸里就可以1-2天内揭开透透气。喷水太多也不好，会烂根噢。⬇️ <br><img data-rawwidth="4000" data-rawheight="3000" src="https://pic1.zhimg.com/123f31b8f0af77aa71218131f2032780_b.jpeg" class="origin_image zh-lightbox-thumb" width="4000" data-original="https://pic1.zhimg.com/123f31b8f0af77aa7121813g"><br>放两个小猫头鹰在里面居住⬇️<br><br><img data-rawwidth="4000" data-rawheight="3000" src="https://pic1.zhimg.com/35748904bfbe6867610a90dd8ed0b244_b.jpeg" class="origin_image zh-lightbox-thumb" width="4000" data-original="https://pic1.zhimg.com/35748904bfbe6867610a90dd8ed0b244_r.jpeg"><br><br><br><b>No.10 空气凤梨（新入手的植物，因为太喜欢它张扬飘逸的造型了！本身就是艺术品呐！麻麻再也不用担心我换盆换土时，搞得十指黑了。）</b><b><br>饲养时长：一个月<br>生存指数：未知（持续观察）<br>暴力照顾：晒着，一礼拜泡次澡。偶尔喷水。</b><br><br>休斯顿棉花糖⬇️我把它搁在练毛笔字用的水盂上，挺配的。<br><img data-rawwidth="3264" data-rawheight="2448" src="https://pic1.zhimg.com/ad3ead73f4bd4cd245e687f744835078_b.jpeg" class="origin_image zh-lightbox-thumb" width="3264" data-original="https://pic1.zhimg.com/ad3ead73f4bd4cd245e687f744835078_r.jpeg"><br>美杜莎，瞧这个妖娆的扭姿，看得我都心动了。⬇️<br><img data-rawwidth="1280" data-rawheight="1280" src="https://pic2.zhimg.com/9542092260b9281e8fc724b1c3be5f89_b.jpeg" class="origin_image zh-lightbox-thumb" width="1280" data-original="https://pic2.zhimg.com/9542092260b9281e8fc724b1c3be5f89_r.jpeg">因为家里还有一个玻璃球，于是在楼下捡了些枯树枝和干浆果拿来造景。瓶子里的是维多利亚和蝴蝶空气凤梨。<br><img data-rawwidth="2345" data-rawheight="2345" src="https://pic3.zhimg.com/26817ba361fe9e4ab1f9fe05cb0ff8f6_b.jpeg" class="origin_image zh-lightbox-thumb" width="2345" data-original="https://pic3.zhimg.com/26817ba361fe9e4ab1f9fe05cb0ff8f6_r.jpeg">做好后是这样的⬇️<br><img data-rawwidth="2389" data-rawheight="2389" src="https://pic4.zhimg.com/6b9293b3bddbefa902b4bce8b6417f6f_b.jpeg" class="origin_image zh-lightbox-thumb" width="2389" data-original="https://pic4.zhimg.com/6b9293b3bddbefa902b4bce8b6417f6f_r.jpeg"><img data-rawwidth="2373" data-rawheight="2373" src="https://pic3.zhimg.com/7c6175adceee62aad61d891577837bde_b.jpeg" class="origin_image zh-lightbox-thumb" width="2373" data-original="https://pic3.zhimg.com/7c6175adceee62aad61d891577837bde_r.jpeg"><img data-rawwidth="2448" data-rawheight="2448" src="https://pic4.zhimg.com/c74bcd0319dc67bd16c24ede0ca7acdf_b.jpeg" class="origin_image zh-lightbox-thumb" width="2448" data-original="https://pic4.zhimg.com/c74bcd0319dc67bd16c24ede0ca7acdf_r.jpeg">空气凤梨真的是一个让人灵感提升的好植物！<br><br><b>No.11 水晶草（如果你很懒，什么都不想管，干花总会是适合你的一款）</b><br><b>饲养时长：三个月<br>生存指数：天长地久（都成干花了想放多久都行）<br>暴力照顾：不用管。</b><br><br>非常百搭！白色的小花朵非常纯美。我买回来时候还是活生的⬇️一大把才20块钱<br><img data-rawwidth="4000" data-rawheight="3000" src="https://pic4.zhimg.com/ebf448d146fdf43c1d61d23e4b5e2dc7_b.jpeg" class="origin_image zh-lightbox-thumb" width="4000" data-original="https://pic4.zhimg.com/ebf448d146fdf43c1d61d23e4b5e2dc7_r.jpeg"><br>现在已经变干花了，但颜色和造型都还在，真的很实惠！很好养啊 ⬇️<br><img data-rawwidth="2448" data-rawheight="2448" src="https://pic2.zhimg.com/3263272e8c31d4a89cf74f8e886dbe95_b.jpeg" class="origin_image zh-lightbox-thumb" width="2448" data-original="https://pic2.zhimg.com/3263272e8c31d4a89cf74f8e886dbe95_r.jpeg"><br>好先写到这，以上所有植物在北京都能活的挺好，题主在南方那更是没有问题。如果今后有新进植物，或者生长情况我会再补充和更新。<br>--------<br>--------<br>--------<br><b>2016.03.13 补充</b><br>原文里推荐的只是部分我养的植物, 有些我自己不确定好不好养，或者太季节性的植物，我先不推荐啦～<br><br>给植物们浇水的时候都会感觉很平静，感谢植物们给我们生活添加生趣。<br><br>附上我的小工具给大家参考。：）<br><img data-rawwidth="1920" data-rawheight="1440" src="https://pic1.zhimg.com/f3a7778fe70ab2143a4e761109274cd8_b.jpeg" class="origin_image zh-lightbox-thumb" width="1920" data-original="https://pic1.zhimg.com/f3a7778fe70ab2143a4e761109274cd8_r.jpeg"><br><img data-rawwidth="1440" data-rawheight="1920" src="https://pic4.zhimg.com/4bd865291b9f619b8c220c7b33b76363_b.jpeg" class="origin_image zh-lightbox-thumb" width="1440" data-original="https://pic4.zhimg.com/4bd865291b9f619b8c220c7b33b76363_r.jpeg"> <span class="answer-date-link-wrap"> <a class="answer-date-link last_updated meta-item" data-tip="s$t$发布于 2016-03-07" target="_blank" href="/question/24678497/answer/89621944">编辑于 14:36</a> </span>

感谢大家这么支持一个业余种植物的。
北京，天蓝，风大。
携众植物晒太阳，向跟大家问安！
----2016.03.13 update【以下原文】推荐些自己养的
室内植物
，
全部自养，全部原创（多图）供大家参考。爱植物的你们长得一定很好看！多点赞鼓励啊！
本人坐标北京，一般…
显示全部

**Comment by ezyang** [comment]
well, it doesn't segfault on `PHP 5.6.19-7+deb.sury.org~wily+2` so maybe see if you can upgrade; PHP 5.4 is not an active PHP release (although HTML Purifier is supposed to support this release.)

**Comment by zengxiaoluan** [comment]
thank you.
just I tested in php  5.5.12,no segfault too.

**Comment by ezyang** [comment]
OK, I'll close for now. I am willing to take simple workarounds to avoid this segfault but it doesn't seem worth figuring out what's causing the segfault to begin with.
