### ISSUE TITLE
Warning Array to string conversion in HTMLPurifier_Printer_ConfigForm_default->render

### ISSUE THREAD

**Issue by AdamPS** [ezyang/htmlpurifier#85]
I surprised no one else is seeing this, so sorry if I'm doing something stupid.

v4.7.0 introduced the warning

> Array to string conversion in HTMLPurifier_Printer_ConfigForm_default->render

This comes from AutoFormat.RemoveEmpty.Predicate where the default value is an array of arrays.  This default also fails to print correctly on the config page:

> colgroup:Array
> th:Array
> td:Array
> iframe:Array
> 

It doesn't seem possible to type in a different value and actually get an array of array. 

This value is also missing from the docs at http://htmlpurifier.org/live/configdoc/plain.html.

**Comment by ezyang** [comment]
Nope, real bug, have fix.

**Comment by AdamPS** [comment]
Great, thanks for the quick fix
