### ISSUE TITLE
How do I use HTMLPurifier?

### ISSUE THREAD

**Issue by bumblebritches57** [ezyang/htmlpurifier#92]
I'm completely new to PHP (although I do know C) I've installed pear and HTMLPurifier through it on my Mac, but how do I actually get it up and running? The guide says something about how I need to include the HTMLPurifier main-equilivent file, but where?

In php.ini? somewhere else?

All I'm trying to do is run it against a few of my HTML files for an ebook, I'm not trying to run it on a live site or anything.

**Comment by ezyang** [comment]
First off, you probably don't want HTML Purifier; something like HTML Tidy (or whatever the newest hotness is) would probably be a better match for your use-case.

HTML Purifier doesn't have a command line runner, you will have to write a small PHP script to do so. Something like

```
<?php
include_once 'HTMLPurifier.auto.php';
$raw = file_get_contents('filename');
$purifier = new HTMLPurifier();
echo $purifier->purify($raw);
```

**Comment by bumblebritches57** [comment]
Thank you! that worked, It lopped off the <head> and <html> sections, but I can just copypasta those.
