### ISSUE TITLE
YouTube not working (iframe)

### ISSUE THREAD

**Issue by opheliadesign** [ezyang/htmlpurifier#93]
First, awesome package! I began using it to eliminate all of the garbage from MSWord copy & paste.

Everything is working great but I **simply cannot** figure out how to allow YouTube videos. I have tried multiple code examples, no matter what the `iframe` tag is always removed. What am I missing here? 

Code:
```
// HTMLPurifier
        $config = \HTMLPurifier_Config::createDefault();

        $config->set('HTML.Doctype', 'HTML 4.01 Transitional');
        $config->set('AutoFormat.RemoveEmpty.Predicate', [
            'colgroup' =>
                [],
            'th' =>
                [],
            'td' =>
                [],
            'o:p' =>
                []
        ]);
        $config->set('AutoFormat.RemoveEmpty', true);
        $config->set('AutoFormat.RemoveEmpty.RemoveNbsp', true);
        $config->set('HTML.Allowed', 'p,span[style|class],a[href|title],abbr[title],acronym[title],b,strong,blockquote[cite],code,em,i,iframe[src|width|height],img[alt|title|class|src|height|width],h1,h2,h3,h3,ol,ul,li,table[class|style],tr,td,hr');
        $config->set('HTML.SafeIframe', true);
        $config->set('URI.SafeIframeRegexp', '%^(\/\/www\.youtube(?:-nocookie)?\.com\/embed\/|\/\/player\.vimeo\.com\/)%');

        $def = $config->getHTMLDefinition(true);
        $def->addAttribute('iframe', 'allowfullscreen', 'Bool');

        $purifier = new \HTMLPurifier($config);

        return $purifier->purify($string);
```

**Comment by ezyang** [comment]
Can you paste the HTML you are trying to allow?

**Comment by opheliadesign** [comment]
Sure! Here you go:

```
<h1>Hello!</h1>
<p>Just trying to get a YouTube video to work</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/F4KD5u-xkik" frameborder="0" allowfullscreen></iframe>
```

**Comment by ezyang** [comment]
The problem is your regex; you're searching for URLs of form `//www.youtube.com` but you need to accept a leading `http:` too.

**Comment by opheliadesign** [comment]
I've tried multiple regex options, that does not seem to be the solution. Could you provide one that actually works with the configuration that I have posted?

**Comment by opheliadesign** [comment]
I tested my regex using http://www.phpliveregex.com/ and it appears valid? That specific regex is directly from the https://github.com/mewebstudio/Purifier default configuration. Thinking that the issue is related to something else.

**Comment by ezyang** [comment]
This works for me:

```
<?php
include_once 'library/HTMLPurifier.auto.php';

$config = HTMLPurifier_Config::createDefault();
$config->set('HTML.SafeIframe', true);
$config->set('URI.SafeIframeRegexp', '%^(https?:)?(\/\/www\.youtube(?:-nocookie)?\.com\/embed\/|\/\/player\.vimeo\.com\/)%');
$purifier = new HTMLPurifier($config);

$raw = '<h1>Hello!</h1>
<p>Just trying to get a YouTube video to work</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/F4KD5u-xkik" frameborder="0" allowfullscreen></iframe>';

echo $purifier->purify($raw);
```

**Comment by opheliadesign** [comment]
Holy cow, it looks like it actually worked! The regex I posted initially isn't what I was testing against, must have been one of my several attempts. The latest was actually `"%^(http://|https://|//)(www.youtube.com/embed/|player.vimeo.com/video/)%"`

So this was all related to regex? Ugh. Thanks for your help!

**Comment by opheliadesign** [comment]
@ezyang Actually, it appears that these two configuration options break it - 
```
$config->set('AutoFormat.RemoveEmpty', true);
$config->set('AutoFormat.RemoveEmpty.RemoveNbsp', true);
```
Any idea why? Trying to reduce as much garbage from MSWord copy & paste as possible, that is my main goal.

**Comment by ezyang** [comment]
Add `iframe` to AutoFormat.RemoveEmpty.Predicate, probably.

**Comment by opheliadesign** [comment]
Thanks a bunch! Solved.
