### ISSUE TITLE
assert() has been disabled for security reasons

### ISSUE THREAD

**Issue by psfpro** [ezyang/htmlpurifier#97]
`vendor/ezyang/htmlpurifier/library/HTMLPurifier/Arborize.php` crashed with PHP Warning `assert() has been disabled for security reasons`
Is it good to use this feature in the finished component?

**Comment by ezyang** [comment]
Yes, there are good reasons to keep asserts in prod, but I am not going to argue strenuously to keep them. Ditched.

**Comment by psfpro** [comment]
Thank you. It will be helpful on some hosts.
