### ISSUE TITLE
Cannot retrieve value of undefined directive HTML.TargetNoreferrer

### ISSUE THREAD

**Issue by istana** [ezyang/htmlpurifier#98]
I've upgraded HTML purifier from v4.6 to 4.8 and two messages start popping up in error_log

```
Tue Sep 27 15:20:43.328747 2016] [:error] [pid 28496] [client ::1:33748] PHP Warning:  Cannot retrieve value of undefined directive HTML.TargetNoreferrer invoked on line 6316 in file /var/www/include/HTMLPurifier.standalone.php in /var/www/include/HTMLPurifier.standalone.php on line 2634

[Tue Sep 27 14:49:31.483688 2016] [:error] [pid 29895] [client ::1:33464] PHP Warning:  Cannot retrieve value of undefined directive CSS.AllowDuplicates invoked on line 10104 in file /var/www/include/HTMLPurifier.standalone.php on line 2634
```

I tried to set it via config, but didn't help:

```
$config->set( 'CSS.AllowDuplicates', TRUE );
$config->set( 'HTML.TargetNoreferrer', TRUE );
```

I just got `Cannot set undefined directive CSS.AllowDuplicates to value invoked on line 14 in file...`

I couldn't find anything about it. I use PHP 5.4.16 (cli) (built: Aug 11 2016 21:24:59) and standalone version. Could you help me?

Thanks

**Comment by ezyang** [comment]
What happens if you reupload the new version of HTML Purifier?

**Comment by istana** [comment]
thanks for a reply @ezyang...what do you exactly mean by reupload the new version of HTML Purifier? I replaced old standalone 4.6 (which works fine) with standalone 4.8 (throws those two warnings - I saw in commits they were added in 4.8) from http://htmlpurifier.org/releases/htmlpurifier-4.8.0-standalone.zip.

**Comment by ezyang** [comment]
What if you run `php maintenance/flush.php`?

**Comment by istana** [comment]
it generated the same standalone file. But I found out that the problem is in disabled caching. Here is a minimal example in which the error occurs:

```
<?php

require_once '../include/HTMLPurifier.standalone.php';

$config = HTMLPurifier_Config::createDefault();
$config->set( 'Cache.DefinitionImpl', null ); //Turn off caching
$config->set( 'HTML.Allowed', '' ); // do not allow any HTML attributes
$purifier = new HTMLPurifier( $config );

echo $purifier->purify('<b> test HTML purifier</b>');
```

**Comment by ezyang** [comment]
Well, if you need it to just work, turn caching on? You want it on anyway.

**Comment by istana** [comment]
yeah, I'll turn it on. Thanks. Should I close? IMHO it's still a bug

**Comment by ezyang** [comment]
We can keep it open, if you can give me instructions to reproduce the problem on a machine different from the one that you have errors on!

**Comment by Leicas** [comment]
I have the same issue "Cannot retrieve value of undefined directive HTML.TargetNoreferrer" using nextcloud/news, I think caching is enabled, but I am not sure...

**Comment by eppfel** [comment]
Same here, but not the CSS one.

**Comment by istana** [comment]
I hope I'll have time to look into this soon

**Comment by ezyang** [comment]
Aha! In fact, the error only occurs if you copy paste htmlpurifier-4.8.0 ON TOP of an old htmlpurifier-4.6.0 install.

**Comment by ezyang** [comment]
To anyone who is seeing this bug, try DELETING the folder that contains htmlpurifier in its entirety (or perhaps moving it to some backup location), and then reunzipping a fresh 4.8.0 into the location. This solved the problem for me. (I managed to get an error like reported here when I ran `cp` using the noclobber option `-n`, which meant that it would not overwrite existing files.)

**Comment by dynasource** [comment]
Im getting this error after installing a fresh 4.9.1
   - Installing ezyang/htmlpurifier (v4.9.1)
[246.0MB/26.88s] Downloading https://api.github.com/repos/ezyang/htmlpurifier/zipball/de82f9845f2a0f9f27abec67d6a4958427e6f5d6

**Comment by ezyang** [comment]
Hi @dynasource, did you delete the old copy of HTML Purifier before installing the new one? What happens if you do so?

**Comment by dynasource** [comment]
Steps (windows 7):
- manually removed the ezyang folder from the vendor folder
- manually removed the ~\AppData\Local\Composer\files\ezyang
- composer update
- 4.9.1 was installed
-> error applies

After this I:
- manually set the version back to 4.8.0 in composer
- composer update
- error is gone

To finish. I am getting the error when running PHP 7.1.2 NTS in CLI mode during a parallel testing session.

**Comment by ezyang** [comment]
What happens if you update to 4.9.1, and then run `php maintenance/flush.php`?

**Comment by istana** [comment]
since I updated the code to 4.9.2 standalone, it no longer prints errors...it just works

**Comment by ezyang** [comment]
OK cool, let's call this fixed!

**Comment by rayfun** [comment]
This is filling my logs REALLY fast!
I deployed 4.9.2, deleting the old folder before.

Error	PHP	Cannot retrieve value of undefined directive Core.AggressivelyRemoveScript invoked on line 352 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901	2017-06-02T14:44:11+0200
Error	PHP	Cannot retrieve value of undefined directive Core.LegacyEntityDecoder invoked on line 337 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901	2017-06-02T14:44:11+0200
Error	PHP	Cannot retrieve value of undefined directive HTML.TargetNoopener invoked on line 279 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/HTMLModuleManager.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901	2017-06-02T14:44:11+0200
Error	PHP	Cannot retrieve value of undefined directive HTML.TargetNoreferrer invoked on line 276 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/HTMLModuleManager.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901	2017-06-02T14:44:11+0200
Error	PHP	Cannot retrieve value of undefined directive Core.AggressivelyRemoveScript invoked on line 352 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901	2017-06-02T14:44:10+0200
Error	PHP	Cannot retrieve value of undefined directive Core.LegacyEntityDecoder invoked on line 337 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901	2017-06-02T14:44:10+0200
Error	PHP	Cannot retrieve value of undefined directive HTML.TargetNoopener invoked on line 279 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/HTMLModuleManager.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901	2017-06-02T14:44:10+0200
Error	PHP	Cannot retrieve value of undefined directive HTML.TargetNoreferrer invoked on line 276 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/HTMLModuleManager.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901	2017-06-02T14:44:10+0200
Error	PHP	Cannot retrieve value of undefined directive Core.AggressivelyRemoveScript invoked on line 352 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901	2017-06-02T14:44:09+0200
Error	PHP	Cannot retrieve value of undefined directive Core.LegacyEntityDecoder invoked on line 337 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901	2017-06-02T14:44:09+0200
Error	PHP	Cannot retrieve value of undefined directive Core.AggressivelyRemoveScript invoked on line 352 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901	2017-06-02T14:44:09+0200

**Comment by ezyang** [comment]
Hi @rayfun, please look at #132 for the latest news. In particular, if you can offer me SSH access to an account on nextcloud which repros the problem, I can investigate.
