### ISSUE TITLE
Plug-and-play install not working

### ISSUE THREAD

**Issue by ppKrauss** [ezyang/htmlpurifier#99]
A red message, "InvalidArgumentException" after run `% composer require "ezyang/htmlpurifier": "dev-master"`,

```
  [InvalidArgumentException]
  Could not find package dev-master at any version for your minimum-stability (stable).
  Check the package spelling or your minimum-stability

  require [--dev] [--prefer-source] [--prefer-dist] ...   ...
```

**Comment by ezyang** [comment]
I don't know much about composer so I don't know how to resolve this. Guidance appreciated.

**Comment by ppKrauss** [comment]
Hi @ezyang, there are another way to install (other Guide?) complete htmlpurifier  package?

**Comment by ezyang** [comment]
Follow this guide maybe? http://htmlpurifier.org/download#Installation

**Comment by johndodev** [comment]
add this to your composer.json : 

```
"minimum-stability": "dev",
"prefer-stable": true,
```

or, better, don't use dev-master: 

    $ composer require "ezyang/htmlpurifier"

**Comment by ppKrauss** [comment]
Hi all, the simplest command (with no *composer.json* addition), `composer require "ezyang/htmlpurifier"`, now is working  fine!

Thanks @johndodev and @ezyang
